### ISSUE TITLE
[POS UI Extensions] Fixed amount discount is not applied by applyCartDiscount

### ISSUE THREAD

**Issue by pablogiralt** [Shopify/ui-extensions#1018]
## Please list the package(s) involved in the issue, and include the version you are using

retail-ui-extensions v1.1.2

## Describe the bug

The applyCartDiscount api method does not applied discount of type "Fixed". 
Discounts of type "Percentage" are applied properly

## Steps to reproduce the behavior:

Executing the following code, logs 'applied successfully' but no discount is added to cart
```
    api.cart.applyCartDiscount('Fixed', `Test Discount`, '10')
    .then(() => {
      console.log('applied successfully')
    })
    .catch((error) => {
      console.error(error)
    });
```

**Comment by NathanJolly** [comment]
The correct string for a Fixed discount is `FixedAmount`. Our documentation is wrong and I'll update it.
