### ISSUE TITLE
POS UI Extensions: Cart's LineItem SKU is undefined for LineItem with an SKU

### ISSUE THREAD

**Issue by dsnvs** [Shopify/ui-extensions#1045]
## Please list the package(s) involved in the issue, and include the version you are using

retail-ui-extensions-react V1.1.2

POS App version: 8.11.1
Build 2080
iPadOS version 16.5.1

## Describe the bug

Inside the Cart state, LineItem.sku is always undefined (even when a product has an SKU).

## Steps to reproduce the behavior:

1. Add a product with an SKU to the cart
1. Use `useCartSubscription()` to get the Cart state and try accessing or reading the SKU.

## Expected behavior

LineItem's SKU is returned.

**Comment by pkhanal** [comment]
The fix for this issue will be available in POS app version 8.20
