### ISSUE TITLE
[Checkout-UI] DateField not updating textfield value when updated

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1049]
## Please list the package(s) involved in the issue, and include the version you are using

checkout-ui-extensions-react ^0.27.0

## Describe the bug

Was looking into upgrading to the new `DateField` component and it seems to be broken when updating the value programatically.

This basically makes the new DateField unusable since the customer's invalid date can't be removed.

```jsx

const [date, setDate] = useState("");

return (
                 <DateField
                    label={label}
                    value={date}
                    disabled={disabledDates}
                    onChange={setDate}
                    onInvalid={(e) => {
                        console.log("clear date");

                        setDate("");
                    }}
                />
                )
```

In the above example, setDate resets the date when an invalid selection is made but value still shows the previous value rather than the new value. DateField seems to only show the updated value when it's typed or selected within the DatePicker component.

## Steps to reproduce the behavior:

1. Add DateField
2. Using React state, update the date value programatically
3. Old value still shown in the DateField textfield component

## Expected behavior

I'd expect setDate("") to reflect within the date field with a blank textfield rather than the previous value.

## Screenshots

I typed in a disabled date which called onInvalid():
![CleanShot 2023-06-29 at 11 45 35](https://github.com/Shopify/ui-extensions/assets/3484527/edec72cb-098c-40d3-9982-b66440344fe5)

onInvalid cleared the date value but it's still shown:
![CleanShot 2023-06-29 at 11 45 31](https://github.com/Shopify/ui-extensions/assets/3484527/255efb23-aac4-4043-92bb-971cd34da16b)

**Comment by oliverigor** [comment]
Hey @gil--, thanks for creating this issue

Just letting you know that we are working on a fix for this, so stay tuned.
Will update here once it's fixed :D

**Comment by gil--** [comment]
Confirmed. Appears fixed on my end. Thanks!
