### ISSUE TITLE
[Branding Api] Issue with image updates in checkout branding upsert.

### ISSUE THREAD

**Issue by onepagecheckout** [Shopify/ui-extensions#1055]
## Please list the package(s) involved in the issue, and include the version you are using
[checkoutBrandUpsert](https://shopify.dev/docs/api/admin-graphql/unstable/mutations/checkoutBrandingUpsert)
## Describe the bug
Image updates for checkout branding returns `invalid_or_missing_media_image` for some images. It seems like this happens due to some checks on image size(width/height) but there is no information on this in the docs.
## Steps to reproduce the behavior:
1. Switch to unstable Admin API version
2. Run checkoutBrandingUpsert mutation(for imageMediaId one of the autopopulated images in development store when created with test data can be used).
```
    mutation checkoutBrandingUpsert($checkoutBrandingInput: CheckoutBrandingInput!, $checkoutProfileId: ID!) {
      checkoutBrandingUpsert(
            checkoutBrandingInput: $checkoutBrandingInput
            checkoutProfileId: $checkoutProfileId
        ) {
             userErrors {
                field
                message
            }
        }
    }
```
with variables
```
    {
      "checkoutProfileId": "gid://shopify/CheckoutProfile/123",
      "checkoutBrandingInput": {
        "customizations": {
          "header": {
            "logo": {
              "image": {
                "mediaImageId": "gid://shopify/MediaImage/456"
              }
            }
          }
        }
      }
    }
```
## Expected behavior
It should update the checkout logo successfully
## Screenshots
![e89ede00ebd822911737dfad6a88a810](https://github.com/Shopify/ui-extensions/assets/138220555/0930ea27-3359-4a36-bdd8-8098a5fb52ee)

**Comment by jun-shop** [comment]
👋 hey there folks - are you by chance uploading an SVG? we don't support this file format

**Comment by r-valchev** [comment]
Hey hey, no we are trying to upload a png file.
