### ISSUE TITLE
[Checkout UI Extensions] Missing 'code' field in useDeliveryGroups hook

### ISSUE THREAD

**Issue by CharlyTalavera** [Shopify/ui-extensions#1083]
Hi! Thanks for shipping the new `useDeliveryGroups` hook! It's amazing and working nicely.

We were giving it a try and it looks like is working pretty nice, but we figured out that there is a field missing. The `service_code` or `code` field. You can find the reference to that field in the [GraphQL definition](https://shopify.dev/docs/api/storefront/2023-07/objects/CartDeliveryOption) as `code` or as `service_code` in the [Carrier Services API](https://shopify.dev/docs/api/admin-rest/2023-07/resources/carrierservice).

But currently, the [useDeliveryGroups hook](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/delivery/usedeliverygroups) only lists the following fields:

- handle
- title
- description

Is there any plan to add the remaining fields (specially the `code`)? That would be nice since we're using that field as identifier to know which one the customer has selected. 

Thanks!

**Comment by gerwinbrunner** [comment]
@dnagoda Do you have an idea about an ETA for it? It is also an issue for our app.

**Comment by gerwinbrunner** [comment]
@dnagoda 
Could you give us a rough idea. We need to think how we would move forward about the blockage we got with this.

Days? Weeks? Months? Years? At all?

Any kind of response would be great.

**Comment by dnagoda** [comment]
It hasn't been reviewed or prioritized. If you have additional context to add to the issue, please do that. It'll help us with the review/prioritization.

**Comment by gerwinbrunner** [comment]
Sure. Here is our use case:

We use the rates at checkout to display specific rates for specific customers. We encode this info into the rates `code` field.

We used to have a plus checkout.liquid script that merchants could use. That script used the code to display additional info.

Now we are trying to replicate that functionality with checkout extensions, but we have no access to the currently selected shipping rate code.

**Comment by CharlyTalavera** [comment]
Hi @dnagoda!

Has this requirement been reviewed or prioritized?

**Comment by dnagoda** [comment]
Hi @CharlyTalavera.

Yes. We've added this to our backlog and will try to get it in for the 2023-10 API version. We'll provide another update when that is confirmed, as well as when it's made available on unstable.

**Comment by gerwinbrunner** [comment]
Great news - looking forward to you update.

**Comment by CharlyTalavera** [comment]
Hi @hheyhhay! I see that you picked this one.

Is there any update about this?

Thanks!

**Comment by sjanczy2** [comment]
Hi folks, just chiming in to say this was successfully shipped and released as part of the `2023-10` API version yesterday: https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/apis/delivery

Going to close this one out but feel free to open a new issue for any questions or concerns
