### ISSUE TITLE
[Checkout UI] Can't select `Checkout::ShippingMethodDetails::RenderExpanded` within the checkout editor

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1094]
## If this related to specific APIs or components, please list them here

Checkout Editor / `Checkout::ShippingMethodDetails::RenderAfter`

## Is your feature request related to a problem? Please describe.

Can't select `Checkout::ShippingMethodDetails::RenderExpanded` within the editor when `Checkout::ShippingMethodDetails::RenderAfter` is also enabled. The editor skips over the spot when dragging an extension.

## Describe the changes you are looking for

Make it possible to drag and drop an extension into RenderExpanded.

## Describe alternatives you’ve considered

n/a

## Additional context

```toml
extension_points = [
  "Checkout::ShippingMethods::RenderBefore",
  "Checkout::ShippingMethods::RenderAfter",
  "Checkout::ShippingMethodDetails::RenderAfter",
  "Checkout::ShippingMethodDetails::RenderExpanded"
]
```

https://github.com/Shopify/ui-extensions/assets/3484527/a8eae11b-4e89-4efc-99aa-757dc5253d0e

**Comment by dnagoda** [comment]
The `ShippingMethodDetails` extension points are not fully released yet. Once fully released, you'll be able to save without error.

**Comment by ginmrt** [comment]
Hi @gil--, our new batch of delivery-related extension points is now fully released, sorry about that! 
I've validated the `ShippingMethodDetails::RenderAfter` extension point myself earlier on a fresh development store, you should be good to go!

**Comment by ginmrt** [comment]
@gil-- 
Can you let me know which store(s)? I only mentioned the `RenderAfter` but from our release perspective those two are part of the same group of extensions. I can check `RenderExpanded` specifically and whether the stores have the expected flag.

**Comment by ginmrt** [comment]
I just double-checked `Checkout::ShippingMethodDetails::RenderExpanded` was working on a development store and on a Shopify Plus store. I'll wait for your response to be able to help further.

**Comment by ginmrt** [comment]
We've released a fix for this, you should now be good to go! Thank you for reporting the issue.

**Comment by gil--** [comment]
Confirmed fixed!
