### ISSUE TITLE
Calling the `useOrder()` hook in the thank you page raises an error

### ISSUE THREAD

**Issue by lucasprag** [Shopify/ui-extensions#1170]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/checkout-ui-extensions v0.27.1

```
"@shopify/checkout-ui-extensions-react@0.27.0":
  version "0.27.0"
  resolved "https://registry.yarnpkg.com/@shopify/checkout-ui-extensions-react/-/checkout-ui-extensions-react-0.27.0.tgz#b3f0f7f2a1d79ba582813961225d855ffb5c1cb0"
  integrity sha512-hash
  dependencies:
    "@remote-ui/async-subscription" "^2.1.14"
    "@remote-ui/react" "4.5.x"
    "@shopify/checkout-ui-extensions" "^0.27.0"
    "@types/react" ">=17.0.0 <18.0.0"
```

## Describe the bug

Unlike the other hooks (such as `useCustomer()`) that just return `undefined` if there isn't data available, if you use the `useOrder()` hook in a checkout extension that renders in the thank you page, it raises an error.

![error](https://github.com/Shopify/ui-extensions/assets/2293178/f1fb843d-1e5f-4b7e-b34a-0d5927e5f599)

I understand that the order is not processed yet when the shopper reaches the thank you page, but if it raises an error, we need to conditionally call hooks -- which breaks the [rules of hooks](https://legacy.reactjs.org/docs/hooks-rules.html) and is therefore not advisable  -- or we need to keep re-structuring our extension which limits our ability to create the best shopper experience, especially if this sort of behaviour propagates to the other hooks.

This case is especially important because the thank you page and the order status page are very close to each other in terms of shopper journey.

## Steps to reproduce the behavior:

1. create a checkout extension
2. render the same extension in both thank you page and order status page 
  ```typescript
render('Checkout::ThankYou::Dynamic::Render', () => <App />);
render('Checkout::OrderStatus::Dynamic::Render', () => <App />);
```
4. use the `useOrder()` hook inside said extension

## Expected behavior

`useOrder()` would just return `undefined` when the extension is rendered in the thank you page, like it was doing a few versions before.

-----

Thank you =)

**Comment by lucasprag** [comment]
Just to be extra clear, the `useOrder()` hook raises [this error](https://github.com/Shopify/ui-extensions/blob/c866b23cbbeb28f21db045f5142b796ed790d18d/packages/ui-extensions-react/src/surfaces/customer-account/hooks/order.ts#L23) which gets in the way of re-using code as described above. Other hooks such as `useEmail()` just don't return the data if that's not available ([ref](https://github.com/Shopify/ui-extensions/blob/c866b23cbbeb28f21db045f5142b796ed790d18d/packages/ui-extensions-react/src/surfaces/customer-account/hooks/buyer-identity.ts#L46)).

**Comment by jamesvidler** [comment]
@lucasprag the `order` API is only available to order status extension targets and will not be available for thank you page extension targets. The error is being thrown to make this more explicit. Is this error causing your extension to crash?

**Comment by lucasprag** [comment]
> Is this error causing your extension to crash?

@jamesvidler Thank you for you reply =) Yes, it's raising the error from the screenshot and making the extension crash in the thank you page.

I understand that the order is only available in the order status extension targets. My point above is that with other hooks, they just return undefined if the data is not available. 

⭐  The problem is that the decision to make the order hook raise an error when using it in other targets -- such as the thank you page targets -- makes it much harder to create an extension that could work on both thank you and order status pages.

This is especially important in this case because these pages are very similar and we (at [Smile](https://smile.io/)) would like to create similar experiences as well without having to work around this sort of problem.

Does it make sense?

**Comment by jamesvidler** [comment]
@lucasprag, yes I can see how it would be better to not throw an error in case. What I might recommend instead would be to attempt to read the `order` this way:

```
function Extension() {
  const { extension } = useApi();
  let order = null;

  if(extension.target === 'Checkout::OrderStatus::Dynamic::Render') {
    const api = useApi('Checkout::OrderStatus::Dynamic::Render');
    order = api.order;
  }
}
```

In the meantime, i'll bring this up with the team to review if we want to continue to do this with our hooks.

**Comment by lucasprag** [comment]
Thank you for considering it. I will also give your suggestion a try 👍🏼

**Comment by leeyowu** [comment]
Hello, because using useOrder on the thank you page is causing an error, I want to confirm how to obtain order information in the current version as of 2nd July 2023. Will there be any way for us to get order information on the thank you page in the upcoming version that will be released in October? @lucasprag @andrewpye

**Comment by lucasprag** [comment]
@jamesvidler so thank you so much for all that. I will close this issue then. 🙇🏼
