### ISSUE TITLE
Extensions cannot be placed in the shipping address section of checkout

### ISSUE THREAD

**Issue by sjanczy2** [Shopify/ui-extensions#1171]
Initially flagged [here](https://github.com/Shopify/ui-extensions/issues/1151#issuecomment-1650942953) along with a follow up screenshot [here](https://github.com/Shopify/ui-extensions/issues/1151#issuecomment-1652313619)
![256332851-8be7b4eb-17b1-4641-b211-b5c825edea99](https://github.com/Shopify/ui-extensions/assets/10068709/69c1c5cd-6852-4bfb-8faa-2701efa390b4)

**Comment by michaelelmgreen** [comment]
Hey @nboliver @gil-- . The fix has shipped for this issue. Thanks again for your feedback.
