### ISSUE TITLE
useSessionToken availability in admin UI extensions

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/ui-extensions#1172]
## Please list the related package(s)

admin-ui-extensions-react

## If this related to specific APIs or components, please list them here

`useSessionToken` like the one that's in the App Bridge and checkout UI extensions.

## Is your feature request related to a problem? Please describe.

We're looking for ways to get an admin session token to communicate with our app backend from an admin block.

## Describe the changes you are looking for

We'd like to be able to perform fetch calls to our app backend like we do with an embedded app. Normally we do this with a session token acquired from the App Bridge and I'm hoping a similar mechanism for getting a current session token is coming to admin blocks unless it's already here and I just missed it!

## Describe alternatives you’ve considered

Some data could be stored in metafields, but keeping heavily updated data in sync from our app to metafields is unlikely to scale well with API call limits. Reaching out more directly to our app would eliminate the need to perform this sync.

## Additional context

None.

**Comment by developit** [comment]
Hi @mbaumbach - the session token you're looking for is actually already being sent automatically when you call `fetch()`. You should see it in the `Authorization` request header:

```js
request.headers.get('Authorization'); // "Bearer abc123"
```
