### ISSUE TITLE
AppMetafields API not consistently returning metafield values

### ISSUE THREAD

**Issue by sjanczy2** [Shopify/ui-extensions#1174]
@gavinballard flagged this on https://github.com/Shopify/ui-extensions/issues/1151#issuecomment-1652880371

**Comment by gavinballard** [comment]
Thanks @sjanczy2 - I have passed along some information via email.

**Comment by sjanczy2** [comment]
Hi folks, this issue has been a bit tricky but here’s the situation as I understand it.
1. Yesterday when an automation closed the issue, a fix went out that should be a partial fix. Specifically, any published extensions should have started properly getting back app metafields. However,
2. This is only true for published extensions, extensions coming from the CLI are still not always getting back the data
3. As @patryk-smc pointed out, I’m not seeing the app metafields on initial render, but on subsequent renders they are there(I’m basing this off of console logs)

So far, we think we know the cause for 2 and are diving deeper. We’ll continue investigating that one followed by 3.

**If you are still seeing app metafields not returned for published extensions(number 1 above) please let us know**

I also saw [this issue come in recently](https://github.com/Shopify/ui-extensions/issues/1186), if it does not share the same root cause as the current issue we’ll continue the conversation there

**Comment by patryk-smc** [comment]
I have been developing my extension for few weeks now and app metafields always seem to be empty array on first render. We just started testing extension on production and on one testing device they were consistently empty, while on other they were empty on first render and fetched afterwards. After few minutes first device started working just fine.

**Comment by KTruong008** [comment]
> **If you are still seeing app metafields not returned for published extensions(number 1 above) please let us know**

Not confirmed but I highly suspect at least one of my merchants is also seeing this issue. He reported today checkout UI components were not showing on his checkout, despite showing up fine last week. Upon further inspection on my end I found the component showing, but only sometimes.

Network tab shows the app loading fine and console didn't show any related errors. My app depends on AppMetafields for component data, and the past several times it stopped showing it was also related to problems with AppMetafields. If the AppMetafields doesn't load properly then my app gets no data and renders nothing, which seems to match in description for this issue. 

With regards to app metafields showing empty array on the first render, I've noticed that as well for months now. It was actually empty for the first several renders, but data always came through eventually in my testing.

**Comment by nboliver** [comment]
> If you are still seeing app metafields not returned for published extensions(number 1 above) please let us know

@sjanczy2 Still seeing it. 

<img width="311" alt="image" src="https://github.com/Shopify/ui-extensions/assets/3094055/2b831b21-c17f-4e86-8d05-60242f7e12f0">

**Comment by gil--** [comment]
Seeing this mostly on one-page checkout where extensions don't consistently load. Not reproducing on three-page. Multiple production merchants reported seeing this behavior.

**Comment by Jay-Plumb** [comment]
+1 we are observing the same problem on our production store where first there is metafield related content in an array but subsequently stores as an empty array

**Comment by elskhn** [comment]
Apologies for all the trouble with this folks. We've shipped out a fix – please let us know if you encounter any more unexpected behaviour.

**Comment by SuspenseFallback** [comment]
Hi @elskhn,

I am trying to develop an app for Shopify. I have scaffolded an extension, and have not changed the code affecting the API:

```
const api = useApi();
```

However, this never gives me the shop metafields, either the `metafields` or the `appMetafields` section (I am trying on CLI). Anything I can do to stop this?

**Comment by elskhn** [comment]
hey @SuspenseFallback, 

make sure you define the metafields in your [extension config](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/configuration#metafields) first. Then, [`useAppMetafields()`](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/apis/metafields#useAppMetafields) should return the shop metafields you are looking for.

**Comment by SuspenseFallback** [comment]
Hi @elskhn,

Thanks for the comment. It turned out that useAppMetafields was asynchronous, which is why it didn't work for me.
