### ISSUE TITLE
[Feature]: Metafield in (Product Merchandise) CartLine

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/ui-extensions#1192]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Hi team,

At the moment we use metafield at checkout in `line_items` to custom UI at checkout page , but with new checkout extension we don't have that with `useCartLines`. 

Can the team provide it or give any some solution to resolve it?

Thank you very much

### Motivation

We use metafield of product to show/hide some UI at checkout page. For now we don't know how to resolve it if we don't have.

**Comment by chienit3bk** [comment]
If I understand correctly, you need to get product metafields ?
For that, you can using Storefront API to get product metafields data to show/hide UI.
More information about here: https://shopify.dev/docs/api/storefront/unstable/objects/Product

**Comment by hoannguyen02** [comment]
> If I understand correctly, you need to get product metafields ? For that, you can using Storefront API to get product metafields data at Checkout Ui Extension to show/hide UI. More information about here: https://shopify.dev/docs/api/storefront/unstable/objects/Product

Yes, can we return it within `useCartLines` in `CartLine` interface ?

**Comment by lemonmade** [comment]
In addition to using the storefront API, you can use the ["app metafields" API](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/apis/standardapi#properties-propertydetail-appmetafields). With this API, you list the metafields you want as a `metafields` key in your `shopify.extension.toml`, and those metafields are queried on a number of objects in checkout, including the products and variants in cart lines. The [`useAppMetafields()`](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks/metafields/useappmetafields) hook lets you look these metafields up based on the results you get from the cart lines:

```ts
import {useCartLines, useAppMetafields} from '@shopify/checkout-ui-extensions-react';

function MyExtension() {
  const firstLine = useCartLines()[0];
  const variantMetafields = useAppMetafields({id: firstLine.merchandise.id});
  const productMetafields = useAppMetafields({id: firstLine.merchandise.product.id});
}
```

**Comment by hoannguyen02** [comment]
> In addition to using the storefront API, you can use the ["app metafields" API](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/apis/standardapi#properties-propertydetail-appmetafields). With this API, you list the metafields you want as a `metafields` key in your `shopify.extension.toml`, and those metafields are queried on a number of objects in checkout, including the products and variants in cart lines. The [`useAppMetafields()`](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks/metafields/useappmetafields) hook lets you look these metafields up based on the results you get from the cart lines:
> 
> ```ts
> import {useCartLines, useAppMetafields} from '@shopify/checkout-ui-extensions-react';
> 
> function MyExtension() {
>   const firstLine = useCartLines()[0];
>   const variantMetafields = useAppMetafields({id: firstLine.merchandise.id});
>   const productMetafields = useAppMetafields({id: firstLine.merchandise.product.id});
> }
> ```

Hi thanks for the suggestion @lemonmade

**Comment by hoannguyen02** [comment]
Thank you all, I have managed to create a map/dictionary based on `useAppMetafields` with metafield key, then check it when loop over cart line item.

Hopefully we have it in `CartLine` like `Attribute` in the future.

**Comment by lemonmade** [comment]
Glad you found a solution, @hoannguyen02. In the future, we plan to support GraphQL-based "input queries" for UI extensions, like we do in Shopify Functions. When declaring data dependencies in an input query, the metafield is directly returned on the cart line's product/ variant fields, which should make this much simpler to accomplish.
