### ISSUE TITLE
useBuyerJourneyIntercept runs more often

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/ui-extensions#1200]
## Please list the package(s) involved in the issue, and include the version you are using

    "@shopify/ui-extensions": "2023.7.x",
    "@shopify/ui-extensions-react": "2023.7.x",

## Describe the bug

Without introducing any changes to my extension, I noticed that useBuyerJourneyIntercept runs on each change of shipping method. Previously it ran only when the button "Continue" (on 3p checkout) or "Pay now" (on 1p checkout) was pressed.

## Expected behavior

useBuyerJourneyIntercept should only run when the button "Continue" (on 3p checkout) or "Pay now" (on 1p checkout) is pressed.

## Additional context

I add metafield to the checkout when the user chooses a specific shipping method. I remove the metafield in the useBuyerJourneyIntercept hook if the user changes their mind and selects a different shipping method and then proceeds. However, I don't want to remove it when the shipping method is changed before the user proceeds, as I want to keep their selection if they decide to go back to the shipping method that sets the metafield.

**Comment by kfalkiewicz** [comment]
@dnagoda It's simple. When you have custom delivery method added by app. You want to block the user checkout as long as the user doesn't "select" / "type" something inside your custom delivery method (for example add additional info etc.). This useBuyerJourneyIntercept should block the checkout for 100% of the users, but it does only for 99% (omits those without metafield).

**Comment by moritz-pv** [comment]
Unbelievable that this gets closed without addressing the issue, and even the gall to add "Please let us know if there's a part of this that wasn't addressed."

This is a bug. It is still present. It was reported here. You should fix it instead of closing the ticket.
