### ISSUE TITLE
Checkout-UI `<Icon />` interactive apperance doesn't inherit hover?

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1282]
## Describe the bug

I feel this is a bug/oversight but if you place an `<Icon />` inside a `<Button>` and use `appearance="interactive"` it won't inherit the button color change on hover/focus which seems wrong.

It looks like currently the icon simply adds color: inherit to the SVG which overrides currentColor which would otherwise inherit color changes on the parent anchor tag.

## Steps to reproduce the behavior:

1.  Add button with an icon set to interactive appearance
2. Hover/Tab focus
3.. No color change on icon but button text correctly changes color.

## Expected behavior

I'd expect that the icon respects the change in color on hover/focus

## Screenshots

Current result:

![CleanShot 2023-08-23 at 19 24 42](https://github.com/Shopify/ui-extensions/assets/3484527/2c4b98c0-b173-4811-a875-a6e3b15e6f43)

Expected result:
![CleanShot 2023-08-23 at 19 19 57](https://github.com/Shopify/ui-extensions/assets/3484527/6a5ff735-db2e-45f3-9f3c-7f6ea780280a)

## Additional context

```jsx
<Button kind="secondary" to="">
                 <Icon
                            appearance="interactive"
                            source="mobile"
                            size="base"
                 />
               Click me
</Button>
```

**Comment by cpeddecord** [comment]
@igor10k is this something your team would handle?

**Comment by simontaisne** [comment]
Hey @gil--, in this scenario, the quick fix would be to opt for the `monochrome` `appearance` for your Icon. This way the Icon will inherit the hover state color of the `Button`.

```tsx
<Button kind="secondary">
  <Icon appearance="monochrome" source="mobile" />
  Click me
</Button>
```
