### ISSUE TITLE
[POS UI] TextField flickering when updating state

### ISSUE THREAD

**Issue by adearriba** [Shopify/ui-extensions#1284]
## Please list the package(s) involved in the issue, and include the version you are using
@shopify/retail-ui-extensions-react V 1.2.0 & 1.3.0

> Note: I updated to 1.3.0 and still the issue persists

## Describe the bug
TextField component render is not working correctly. The new state seems to take time to update.

## Steps to reproduce the behavior:
1. Create a useState
2. Add a TextField component
3. Set the value to the state value and onChange to the setState function.
4. Test the app

## Expected behavior
The component renders the new state without flickering

## Screenshots
https://github.com/Shopify/ui-extensions/assets/4951003/2b816b57-960a-465a-a4aa-cc892de0e1e3

## Additional context
Simple code:

```javascript

export function FormScreen() {
    const [name, setName] = useState("")

    return(
        <Screen name="NewClientForm" title="Nuevo Cliente">
            <ScrollView>
                <TextField 
                    label="Name" required 
                    placeholder="Name" 
                    value={name} 
                    onChange={setName} 
                />
            </ScrollView>
        </Screen>
    );
}
```

**Comment by FlantasticDan** [comment]
I've been able to replicate this issue as described in `v1.2.0`.  I don't know if it's related but similarly I also could not get a TextField to work in the non-react flavor of retail-ui-extensions and posted about that [here](https://community.shopify.com/c/technical-q-a/textfield-in-pos-ui-extensions-does-not-store-data/td-p/2196934).

**Comment by adearriba** [comment]
Can someone from Shopify take a look at this issue. We have impacted customers and there is no alternative.
