### ISSUE TITLE
Checkout Footer / Checkout Policies

### ISSUE THREAD

**Issue by maks-afew** [Shopify/ui-extensions#1387]
## Please list the related package(s)

checkout-ui-extensions

## If this related to specific APIs or components, please list them here

AFAIK there is no API or Component for that

## Is your feature request related to a problem? Please describe.

I see no way to modify the checkout footer or to modify the modals where the policies are being rendered

## Describe the changes you are looking for

Being able to modify checkout footer, especially regarding policy links - props like `href` or `target`. Being able to add other links and remove standard policy links.

## Describe alternatives you’ve considered

I haven't found any alternative

## Additional context

We have added policies as a HTML code in the shop settings and they are rendered beautifully in the shop frontend, but the checkout modal box doesn't apply the html and renders pretty much plain text. In the checkout.liquid we solved it by modifying policy links with javascript, adding target="_blank". We also have another store running where we replace policy links with some other links.

**Comment by elskhn** [comment]
hello there! We are currently working on a project to enable header & footer customizations. As part of this project, new extension targets in the Checkout header & footer will be added. 

You will be able to create a footer extension with custom links & modals then.

**Comment by jun-shop** [comment]
The above-mentioned feature is live. Here is a relevant [tutorial](https://shopify.dev/docs/apps/build/checkout/customize-footer?extension=react). I'm closing this out as done, but feel free to circle back with questions.
