### ISSUE TITLE
useSubscription: Uncaught TypeError: Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by peepers-rick** [Shopify/ui-extensions#1400]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/app": "3.49.5",
"@shopify/cli": "3.49.5"
"react": "^17.0.0",
"@shopify/ui-extensions": "2023.7.x",
"@shopify/ui-extensions-react": "2023.7.x"

## Describe the bug

```
export default reactExtension(
  'purchase.checkout.shipping-option-list.render-after',
  () => <Extension />,
);
```

`const { target } = useApi()` always results in undefined. Then if I try `const shippingOption = useSubscription(target)`, I get `Uncaught TypeError: Cannot read properties of undefined (reading 'current')` at `useSubscription`

## Steps to reproduce the behavior:

1. new checkouts UI extension
2. import useSubscription and call useSubscription
3. observe error

## Expected behavior

Expect to get a shippingOption returned from useSubscription

**Comment by victorvilarocket** [comment]
why has this incidesnt been closed? The error also appears with  `purchase.checkout.shipping-option-item.render-after` extension target

**Comment by jamesvidler** [comment]
@victorvilarocket could you share an example of extension code that reproduces this behaviour? Just an FYI that as of version `2023-10` this is now accessible via the react hook [useShippingOptionTarget](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/apis/delivery#useShippingOptionTarget).
