### ISSUE TITLE
know more about the webpixel

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/ui-extensions#1416]
@shopify-admins 

thanks for the sharing the knowledge of the web pixel.

I am building the web pixel app extension can be run the gtm script code like third party js code in the app pixel.

how to migrate script_tag or theme app extension to the webpixel ?

can I write any js code in the js files ?

what are limitation for web pixel ?

Facebook pixel can be work with app pixel ?

**Comment by cpeddecord** [comment]
Hopefully we can answer most of your questions here:

https://shopify.dev/docs/api/web-pixels-api

If you'd like to join us on our Discord, you can do so here: https://discord.com/invite/shopifydevs

**Comment by adventuretocode** [comment]
@cpeddecord  Thanks for the I am already joined the discord community I asked their but still not response.
