### ISSUE TITLE
Checkout UI: `Cannot call 'applyMetafieldChange()' on target 'purchase.checkout.delivery-address.render-after'.`

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1422]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/ui-extensions: "^2023.10.0",
@shopify/ui-extensions-react: "^2023.10.0",

## Describe the bug

It seems calling the apply metafield hook on the new `purchase.checkout.delivery-address.render-after` target does not work? Is this expected or just a bug?

## Steps to reproduce the behavior:

1. Mount an extension to the `'purchase.checkout.delivery-address.render-after'` target
2. Call applyMetafieldChange
3. A console error will happen

## Expected behavior

Same behavior as `'purchase.checkout.delivery-address.render-before'`

**Comment by elskhn** [comment]
We've pushed out a fix for this – please let us know if you see any other weird behaviour
