### ISSUE TITLE
How to add styles to the checkout-ui component

### ISSUE THREAD

**Issue by Pengzhenglong** [Shopify/ui-extensions#1429]
## Additional context

```[tasklist]
### Tasks
```

**Comment by Pengzhenglong** [comment]
Adding class names or styles to components does not take effect. Is there any way to add style settings?

**Comment by cpeddecord** [comment]
hi @Pengzhenglong, UI Extensions don't accept class names or styles individually, rather they accept what global branding primitives a checkout already has. You can find documentation here ([Advanced Checkout Branding](https://shopify.dev/docs/apps/checkout/advanced-checkout-branding)) for more information.

UI Extension do, however, accept various spacing, layout, and/or color properties. Given our [`BlockLayout` component](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/components/structure/blocklayout) as an example, you have access to `spacing`, `rows`, and `border` properties to name a few.
