### ISSUE TITLE
[Checkout UI] applyCartLinesChange often fails with "Could not apply line item changes"

### ISSUE THREAD

**Issue by FrankHeijden** [Shopify/ui-extensions#1436]
## Please list the package(s) involved in the issue, and include the version you are using
```
@shopify/ui-extensions 2023.10.0
@shopify/ui-extensions-react 2023.10.0
react ^18.2.0
```
## Describe the bug
Applying line item changes (in my case: only changing the line item attributes) often fails with the message "Could not apply line item changes". Unfortunately, this message is all that is returned, and no other feedback is given as to why it fails.

This issue also seems inconsistent, sometimes the changes do apply without an error and sometimes the error does appear.

I am applying the line item change in `purchase.checkout.cart-line-item.render-after`, could this be because of a large cart, triggering a lot of line item changes causing the endpoint to ratelimit?

## Expected behavior
A better indication what might be the actual reason for failing to apply the change. 

## Screenshots
<img width="482" alt="Screenshot 2023-10-12 at 13 02 52" src="https://github.com/Shopify/ui-extensions/assets/22407829/4292bf13-2d20-420d-9655-727c38eaafc9">

**Comment by Briggzly** [comment]
same thing for me :(

**Comment by rbarreca** [comment]
Same here. Intermittently failing.

**Comment by awd** [comment]
Also experiencing the same issue with the same callback. Would love to know why this is happening, is it a case of too many calls (think of a user hitting a checkbox too many times) or some other state of the cart?

**Comment by iamharshad** [comment]
Any update on this? or any solution for this?

**Comment by iamharshad** [comment]
@Alopwer if we are using "purchase.checkout.block.render" then we are not able to move UI section.

**Comment by iamharshad** [comment]
@FrankHeijden,

Could you please confirm if you're using the `useBuyerJourneyIntercept` hook?

In my case, I encountered some interesting scenarios. Initially, I was utilizing the `useBuyerJourneyIntercept` hook for the blocking process. However, upon removing that code, I noticed that my API failure issues resolved.

I suspect that the API call operation and the `useBuyerJourneyIntercept` hook might not be working properly together.

**Comment by FrankHeijden** [comment]
> @FrankHeijden,
> 
> 
> 
> Could you please confirm if you're using the `useBuyerJourneyIntercept` hook?
> 
> 
> 
> In my case, I encountered some interesting scenarios. Initially, I was utilizing the `useBuyerJourneyIntercept` hook for the blocking process. However, upon removing that code, I noticed that my API failure issues resolved.
> 
> 
> 
> I suspect that the API call operation and the `useBuyerJourneyIntercept` hook might not be working properly together.
> 
> 

I am not using the `useBuyerJourneyIntercept` hook, for me at least this occurs without that hook as well sadly.

**Comment by Subscribfy** [comment]
Hi

im I in the same situation? Is there any ETA for when it will be resolved?

**Comment by spatariu** [comment]
Can somebody please solve this?

**Comment by irahulranjan** [comment]
a retry based on a delay seems to be the only solution right now @spatariu

**Comment by Subscribfy** [comment]
> a retry based on a delay seems to be the only solution right now @spatariu

Not in our case. @irahulranjan  do you have an ETA for when it will be repaired? @iamharshad

**Comment by mj991218** [comment]
@irahulranjan 🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆
100% agree with your opinion.
Delay by setTimeout is indeed the perfect solution for this issue.

**Comment by LouiseEH** [comment]
I get "Could not apply line item changes, negotiation was stale." although that is not one of your options @kumar303

**Comment by jamesvidler** [comment]
@rbarreca Yes, this is a known limitation right now. If you receive a state negotiation result, you should re-try the change. Generally, these need to happen one-at-a-time. We are looking at how we can improve this experience, but we don't have a timeline to share yet.

**Comment by dnagoda** [comment]
We deloyed a fix for the the week of December 9th.

**Comment by dnagoda** [comment]
@rbarreca The fix adds better handling of applyCartLineChanges (and similar async API calls), with a focus on avoiding stale negotiation results.
