### ISSUE TITLE
[Checkout UI] Using tel: on Link crashes checkout

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1451]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/ui-extensions": "^2023.10.0",
"@shopify/ui-extensions-react": "^2023.10.0",

## Describe the bug

When using the `<Link>` UI component, checkout will completely crash if we specify a tel: url origin with the external prop. Removing the external prop will prevent the crash from occurring. This is happening both on a dev store and in a production checkout instance.

## Steps to reproduce the behavior:

```jsx
return (
   <Link to="tel:+123" external>Call me</Link>
)
```

It seems to expect an HTTPS origin on external links possibly due to how it opens a new tab.

## Expected behavior

I'd expect checkout not to completely crash, especially in production.

## Screenshots

![CleanShot 2023-10-19 at 11 43 24@2x](https://github.com/Shopify/ui-extensions/assets/3484527/579a5102-0d11-42ef-83a9-a59e50d0b222)

**Comment by igor10k** [comment]
Thanks for the report and sorry for a late reply!

This should be fixed now. Feel free to re-open the issue if you see this happening again.
