### ISSUE TITLE
purchase.cart-line-item.line-components.render extension point is not showing up in the customiser 

### ISSUE THREAD

**Issue by bask-code** [Shopify/ui-extensions#1462]
## Package(s) involved in the issue

@shopify/ui-extensions: 2023.10.x
@shopify/ui-extensions-react: 2023.10.x

## Describe the bug

I am trying to enable a purchase.cart-line-item.line-components.render extension in the customiser after deployment of the extensions. But it keeps saying that the app block is not available. In development mode the extension is working fine. I tested this with a really clean UI extension point. 
Other extension points like 'purchase.checkout.cart-line-item' are working fine. 

## Steps to reproduce the behavior:

1. Create a new checkout UI extension 
2. Change the extension point in the toml and javascript file of the extension
3. Run `npm run dev` to check if the extension is showing in a development checkout. 
4. Run `npm run deploy` to release a new version of the app
5. After install it is not possible to enable the extension in the customiser. 

## Expected behavior
When you can enable a 'purchase.checkout.cart-line-item' it should also be possible to enable 'purchase.cart-line-item.line-components.render'  in the customiser. 

## Screenshots
![Screenshot 2023-10-18 at 10 55 11](https://github.com/Shopify/ui-extensions/assets/78367411/043a9023-d5e6-41aa-b0f7-e4c56b0d2d01)

**Comment by bask-code** [comment]
Hi @kumar303 @denislins,

Any update on this? :)

**Comment by jun-shop** [comment]
here's the related epic https://github.com/Shopify/checkout-web/issues/27685 @alxclark @denislins since the extension target is now private, is the recommendation to not build for it?

**Comment by denislins** [comment]
Hi @bask-code,

While exploring how we could best expose `purchase.cart-line-item.line-components.render` extension targets on the checkout editor, we raised a few points internally that made us reconsider how we want this target to work, and thus what the ideal editor/merchant experience would be.

In the meantime, we've made the decision to temporarily remove this extension target from our extensibility platform - we don't want partners to build extensions using an extension target we know might change, as it wouldn't benefit anyone. We understand you and a few other partners may have already built extensions using it, however - we apologize for the bumpy road here.

I will close this issue for now, but keep an eye out for updates on our docs/developer changelog - I don't have a specific timeline to share with you at this point, but I can promise you we still want to expose this target, and when we do so it will work even better than it did before.

**Comment by bask-code** [comment]
Hi @denislins 

Thanks for the explanation. At least I have something to explain to the client now :)

**Comment by avanfeel** [comment]
Thanks @denislins , to avoid confusion among the community, it would be great if the documentation is updated based on what you mentioned above.

<img width="592" alt="Screenshot 2024-07-07 at 6 40 29 PM" src="https://github.com/Shopify/ui-extensions/assets/903722/3828aa6b-ee9a-47d8-8e87-59016f3ebfdd">
