### ISSUE TITLE
Updated Delivery Address on Shop Pay is not shown as a selected

### ISSUE THREAD

**Issue by robinhosanee** [Shopify/ui-extensions#1468]
## Please list the package(s) involved in the issue, and include the version you are using
api_version = "2023-10"
@shopify/shopify_function": "0.1.0"
@shopify/ui-extensions": "2023.10.x"
@shopify/ui-extensions-react": "2023.10.x"

## Describe the bug
After updating the delivery address using the api useApplyShippingAddressChange,  the updated address is not displayed as a selectable address on Shop Pay. Although the address is updated, the UI is not very clear as a different address is set as selected.

## Steps to reproduce the behavior:
1. Update delivery address to custom address using api useApplyShippingAddressChange
2. Go to Shop Pay
3. Updated Address is not in the list of selectable addresses

## Expected behavior
Updated Address should be selectable and set as selected

Updated address is not part of the selectable address list
![image](https://github.com/Shopify/ui-extensions/assets/31942027/ad00ce1d-de67-4509-b295-73e5e69763fd)

Updated address is only shown when addresses list is collapsed
![image](https://github.com/Shopify/ui-extensions/assets/31942027/1af7125f-f04e-472f-8f3a-cc12b6068fe1)

**Comment by cpeddecord** [comment]
@robinhosanee Shop Pay uses a known address for a particular customer.

If `useApplyShippingAddressChange` was used in guest checkout and then a customer elects to use Shop Pay, we don't carry the values forward, we will instead elect the use known address(es).
