### ISSUE TITLE
`<Link>` component is rendered with no content

### ISSUE THREAD

**Issue by eugeniodepalo** [Shopify/ui-extensions#1471]
## Please list the package(s) involved in the issue, and include the version you are using

```json
"react": "^17.0.0"
"@shopify/ui-extensions": "2023.7.x"
"@shopify/ui-extensions-react": "2023.7.x"
```

## Steps to reproduce the behavior:

1. Generate an Admin Block extension through the CLI
2. Modify `BlockExtension.tsx` as follows:
```typescript
import {
  reactExtension,
  useApi,
  AdminBlock,
  BlockStack,
  Text,
  Link,
} from "@shopify/ui-extensions-react/admin"

// The target used here must match the target used in the extension's toml file (./shopify.extension.toml)
const TARGET = "admin.product-details.block.render"

export default reactExtension(TARGET, () => <App />)

function App() {
  // The useApi hook provides access to several useful APIs like i18n and data.
  const { data } = useApi(TARGET)
  console.log({ data })

  return (
    // The AdminBlock component provides an API for setting the title and summary of the Block extension wrapper.
    <AdminBlock summary="3 items">
      <BlockStack>
        <Text fontWeight="bold">
          Access your dashboard from:{" "}
          <Link to="https://keygen.sh">https://keygen.sh</Link>
        </Text>
      </BlockStack>
    </AdminBlock>
  )
}
```
2. Load the admin page for a product
3. Observe that the link is rendered with no content

## Expected behavior

The `Link` should render with the expected content, instead it renders an empty node. 

### CLI prompts
<img width="337" alt="Screenshot 2023-10-25 at 19 18 24" src="https://github.com/Shopify/ui-extensions/assets/151741/a01d2cf0-00f4-43a0-a826-80d077428607">

### Rendered DOM
<img width="415" alt="Screenshot 2023-10-25 at 19 21 14" src="https://github.com/Shopify/ui-extensions/assets/151741/ed4dbfa4-a7cd-4d7d-95a2-72b23fbce7a2">

### Rendered Admin Block
<img width="637" alt="Screenshot 2023-10-25 at 19 21 42" src="https://github.com/Shopify/ui-extensions/assets/151741/5fd867a0-aa0d-42dc-a873-e804fa3fed58">

**Comment by cpeddecord** [comment]
@olavoasantos is there a proper backlog to put this in?

**Comment by dnagoda** [comment]
Thanks for the update. I'm going to close this one and we can track progress on the new issue.
