### ISSUE TITLE
[Checkout UI] `purchase.checkout.cart-line-item.render-after` does not render in order summary on mobile one-page checkout

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1483]
## Describe the bug

Currently an extension added to the line items does not show within the mobile dropdown order summary. This means important line item information such as "Final sale" does not show to the customer properly.

## Steps to reproduce the behavior:

1. Add an extension in the editor to `purchase.checkout.cart-line-item.render-after`
2. Ensure one-page and mobile, open the order summary and the block is missing

## Expected behavior

Merchants expect that checkout extensions added to `purchase.checkout.cart-line-item.render-after` render in both the order summary and the footer order summary on mobile one-page checkout. 

### Order summary dropdown
![CleanShot 2023-10-30 at 11 54 09](https://github.com/Shopify/ui-extensions/assets/3484527/d5a074d9-dfde-4633-b81a-15e36693de4b)

### Footer order summary
![CleanShot 2023-10-30 at 11 54 02](https://github.com/Shopify/ui-extensions/assets/3484527/f70ac5d9-18b2-41a6-bd8c-5e52858ecf44)

### Editor setup

![CleanShot 2023-10-30 at 11 57 44](https://github.com/Shopify/ui-extensions/assets/3484527/f14c6d68-0f2a-41c3-8284-2f3cd1b63c9d)

**Comment by sns-0987654321** [comment]
Is there any news about updates or improvements?

**Comment by moptix10** [comment]
I have the same issue

**Comment by gil--** [comment]
confirmed fix. thank you team!

**Comment by gil--** [comment]
I think it might have been rolled back or regressed. Will reopen as I can confirm it doesn't appear to be fixed anymore.

**Comment by huel-ollie** [comment]
Hi, I've been pointed here from a Shopify support chat. We're also experiencing this issue, is there a rough ETA on a fix for it? We're running some custom discount validation and the errors are only showing in the one area which is very confusing for users seeing discounts being removed.

**Comment by jun-shop** [comment]
👋 Hey folks - wanted to confirm that this regression is no longer happening? I wasn't able to reproduce on my own dev shop. Extensions targeting the `...cart-line-item.render-after` extension target appear in both order summary sections in mobile on one-page checkouts for me. Are you still experiencing this issue?

**Comment by gil--** [comment]
Confirming extensions added to `...cart-line-item.render-after` show in both order summaries on mobile for 1 Page checkout.

**Comment by edhgoose** [comment]
Shopify Support have recommended that we re-raise the issue as this issue is now closed. 

I've re-raised as #2218.
