### ISSUE TITLE
`<Link>` component is not rendering `target` attribute

### ISSUE THREAD

**Issue by eugeniodepalo** [Shopify/ui-extensions#1484]
## Please list the package(s) involved in the issue, and include the version you are using

```json
"react": "^18.0.0"
"@shopify/ui-extensions": "2023.10.x"
"@shopify/ui-extensions-react": "2023.10.x"
```

## Steps to reproduce the behavior:

1. Generate an Admin Block extension through the CLI
2. Modify `BlockExtension.tsx` as follows:
```typescript
import {
  reactExtension,
  useApi,
  AdminBlock,
  BlockStack,
  Text,
  Link,
} from "@shopify/ui-extensions-react/admin"

// The target used here must match the target used in the extension's toml file (./shopify.extension.toml)
const TARGET = "admin.product-details.block.render"

export default reactExtension(TARGET, () => <App />)

function App() {
  // The useApi hook provides access to several useful APIs like i18n and data.
  const { data } = useApi(TARGET)
  console.log({ data })

  return (
    // The AdminBlock component provides an API for setting the title and summary of the Block extension wrapper.
    <AdminBlock summary="3 items">
      <BlockStack>
        <Text fontWeight="bold">
          <Link to="https://keygen.sh" target="_blank">Keygen dashboard</Link>
        </Text>
      </BlockStack>
    </AdminBlock>
  )
}
```
2. Load the admin page for a product
3. Observe that the link is rendered with no `target` attribute

## Expected behavior

The `Link` should render with the `target` attribute as specified.

### CLI prompts
<img width="337" alt="Screenshot 2023-10-25 at 19 18 24" src="https://github.com/Shopify/ui-extensions/assets/151741/a01d2cf0-00f4-43a0-a826-80d077428607">

### Rendered DOM
<img width="446" alt="Screenshot 2023-10-30 at 20 32 39" src="https://github.com/Shopify/ui-extensions/assets/151741/a820896a-406a-4a28-8ecf-93519202a70a">

**Comment by peepers-rick** [comment]
I don't know if you need a separate issue for this but same behavior on the `<Button>` component
