### ISSUE TITLE
[Checkout UI] Localization markets is undefined when logged in

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1488]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/ui-extensions": "^2023.10.0",
"@shopify/ui-extensions-react": "^2023.10.0",

## Describe the bug

When referencing either the extension api `useApi()` or `useLocalizationMarket()`, the market data is undefined when logged into checkout. This appears to be the case for both one-page and three-page checkout on new customer accounts.

## Steps to reproduce the behavior:

1. const market = useLocalizationMarket();
2. market is undefined

## Expected behavior

Markets should show the same information whether logged in or logged out.

**Comment by kumar303** [comment]
Thanks for your patience, Gil. This was recently fixed. Feel free to re-open if it's not fully fixed for you.
