### ISSUE TITLE
Add "id" parameter to onChange callback for Admin UI Checkbox component

### ISSUE THREAD

**Issue by studioforty9-dev** [Shopify/ui-extensions#1546]
## Please list the related package(s)

admin-ui-extensions-react

## If this related to specific APIs or components, please list them here

Checkbox - https://shopify.dev/docs/api/admin-extensions/2023-10/components/forms/checkbox

## Is your feature request related to a problem? Please describe.

The `onChange` callback only includes a boolean parameter. So it's not possible to distinguish between multiple checkboxes without giving them a specific callback function each. This isn't possible where Checkbox components are dynamically generated.

## Describe the changes you are looking for

Make the Checkbox component similar to the Polaris Checkbox component where it also includes an `id` parameter:

https://polaris.shopify.com/components/selection-and-input/checkbox

## Describe alternatives you’ve considered

A multiselect option on the Select component. This also isn't currently available.

**Comment by studioforty9-dev** [comment]
Thanks @MitchLillie - `ChoiceList` is working well.

**Comment by BARK-CMORENO** [comment]
Hi @MitchLillie @studioforty9-dev same issue with me and I'm a bit new to react. To my understanding is that it was solved by using the `unstable` version. So what I did is to update the `package.json` to have these values:
```
{
  "name": "test-action",
  "private": true,
  "version": "1.0.0",
  "license": "UNLICENSED",
  "dependencies": {
    "react": "^18.0.0",
    "@shopify/ui-extensions": "unstable",
    "@shopify/ui-extensions-react": "unstable"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "react-reconciler": "0.29.0"
  }
}
```

Then deleted the `node_moduels` directory then ran `npm install` to install the modules/dependencies again. Though, even doing that, it seems that the `ChoiceList` component is still not present.

Did I miss something here or am I doing it the wrong way?
