### ISSUE TITLE
TY Page UI extension component isn't rendered after a Post Purchase step

### ISSUE THREAD

**Issue by ihnat-els** [Shopify/ui-extensions#1563]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/checkout-ui-extensions-react": "0.27.3",
"@shopify/post-purchase-ui-extensions-react": "0.13.4",
```

## Describe the bug

If both Post-purchase and Thank you page extensions are enabled for a single checkout process, the Thank you page extension callback isn't triggered.
When a customer goes through the Post-purchase step and accepts or declines the extension's offer, the customer is landed on the Thank you page, where the extensions are not available at all. 
If I make the Post Purchase step skipped, the Thank you page extension works properly.

## Steps to reproduce the behavior:

1. Create Post-purchase and Thank you page extensions using the same app
2. Make sure a Post-purchase extension is enabled
3. Make sure a Thank you page extension is enabled
4. Create an order as a customer and navigate to the post-purchase step
5. Accept or decline the post-purchase extension's offer
6. Land on the Thank you page
7. `Checkout::ThankYou::Dynamic::Render` callback is NOT executed. The behavior is the same as if the checkout extension would be disabled in the Shopify Theme customizer. 

## Expected behavior

1-6 steps
7. The Thank you page extension `Checkout::ThankYou::Dynamic::Render` callback is triggered

## Additional context

If I repeat the same steps but make the Post-purchase step skipped (not being shown to a customer), the Thank you page extension works fine.

**Comment by akatigbak** [comment]
hi there! This issue should be resolved now
