### ISSUE TITLE
Powered by alignment is off

### ISSUE THREAD

**Issue by themarkappleby** [Shopify/ui-extensions#1647]
The alignment of the app block powered by UI is slightly incorrect. When not in its hover state, the app icon should align with the app block's content. This same issue is also present in the app action modal.

## Expected

![Image](https://github.com/Shopify/ui-extensions/assets/1360097/94a05558-8209-4891-ab1f-b42b8ffb601e)

## Actual

![Image](https://github.com/Shopify/ui-extensions/assets/1360097/77c63ee0-919c-4cbe-9b27-bc30016b2d24)

**Comment by AaronSpringut** [comment]
See the prototype for how this should look: https://minerva.shopifycloud.com/auth/minerva?request=27517eb0-cea8-43cc-beee-2ac3652746dc&rd=https://0d80fbbc23ca406ea468f13e7a53f10b.changeme.shopifynetwork.com%2FcardCTARevised

**Comment by AaronSpringut** [comment]
Look into using negative margin so when someone else takes this component and tries to align it to their content, they dont make the same mistake.
