### ISSUE TITLE
PhoneField Component do not show options in the list of countries for choosing the phone prefix

### ISSUE THREAD

**Issue by Ciull0** [Shopify/ui-extensions#1651]
## The expected behaviour is a populated list of countries, from where i can select the phone prefix

when typing a phone number, the flag show up correctly based on the typed prefix.

The documentation of the component clearly states that it's possible. (https://shopify.dev/docs/api/checkout-ui-extensions/2024-01/components/forms/phonefield) and do not supports attributes to enable/disable this feature.

As seen in the screenshot attached, when clicking on the flag to change the phone prefix, and empty option list appears.

![Error_PhoneField_Flag_selection](https://github.com/Shopify/ui-extensions/assets/70094182/cb4083ae-3c59-47b1-acb3-d6b2c141568a)
![Flag_list_empty](https://github.com/Shopify/ui-extensions/assets/70094182/4dd8212b-2a19-4b30-9a14-d19d4f29cead)

**Comment by Ciull0** [comment]
https://github.com/Shopify/ui-extensions/assets/70094182/09b9a7a2-a8ba-4098-acad-bf3bbe4e6833

**Comment by Ciull0** [comment]
https://github.com/Shopify/ui-extensions/assets/70094182/b29f85c2-014d-4be4-9b57-1b6c429d69aa

**Comment by jun-shop** [comment]
👋 Hi @Ciull0 are you able to provide any information around your usage of PhoneField like a code sample? I'm having trouble reproducing what you're seeing. What browser are you using?
