### ISSUE TITLE
The Sheet component is missing from the package - @shopify/ui-extensions-react

### ISSUE THREAD

**Issue by AlexVasVas** [Shopify/ui-extensions#1787]
## Please list the package(s) involved in the issue, and include the version you are using

- @shopify/app@3.56.3
- @shopify/cli@3.56.3
- @shopify/ui-extensions-react@2024.1.1
- @shopify/ui-extensions@2024.1.1
- @types/react@18.2.60
- react-reconciler@0.29.0
- react@18.2.0

## Describe the bug

Running the **npm run dev** command result in the following error message:

 extensions/test-checkout-extension/src/Checkout.jsx:8:2: ERROR: No matching export in
    "node_modules/@shopify/ui-extensions-react/build/esm/surfaces/checkout.mjs" for import "Sheet"

## Steps to reproduce the behavior:

1. In order to test the **Sheet** component I created a new blank JavaScript React checkout extension
2. After that, I updated the **@shopify**, **@shopify/ui-extensions-react**, and **@shopify/checkout-ui-extensions-react** making sure that they are using the latest versions. The versions can be checked at the beginning of my issue description.
3. After that, I copied the example provided in the **Sheet** component's [documentation](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/components/overlays/sheet) and applied the code to my new checkout extension
4. Then I execute the **npm run dev command** which resulted in the error message i provided above.

## Expected behavior

The **Sheet** component to be loaded successfully.

## Screenshots

This is a video showcasing the version of the packages and the error - https://monosnap.com/file/w6IcdcoJBt3blvBmpRdfzxcL3CrtzO

**Comment by cpeddecord** [comment]
@AlexVasVas it's part of unstable and unstable often has releases that might not get picked up in your lockfile. If you find that you've installed unstable, re-creating your lockfile often does the trick.
