### ISSUE TITLE
Company Name is not being updated/cleared when using accelarated checkout

### ISSUE THREAD

**Issue by robinhosanee** [Shopify/ui-extensions#1808]
Checkout UI Extension API Version "2024-01"

## Describe the bug
After filling in shipping details on the Shopify checkout and proceeding to the shipping step, if user returns to information step and proceeds to use an accelarated checkout (e.g Apple Pay), the shipping company name if submitted is not being cleared if the accelarated does not pass a company name back to Shopify.

## Expected behavior
If no company name is passed from the accelarated checkout, it should be cleared and not hold in the order information.

**Comment by jarthorn** [comment]
Thanks for the bug report but this does not appear to be an issue relating to UI extensions. Please contact Shopify support for assistance with this.
