### ISSUE TITLE
applyAttributeChange does not work if the order is submitted as draft order (for B2B customer)

### ISSUE THREAD

**Issue by cupnoodle** [Shopify/ui-extensions#1816]
## Please list the package(s) involved in the issue, and include the version you are using
"@shopify/app": "3.57.0",
"@shopify/cli": "3.57.0"
"@shopify/ui-extensions": "2024.1.x"

## Describe the bug

For a B2B customer with company that has "Submit all orders as drafts for review" enabled, when they submit an order for review, the attribute value applied using applyAttributeChange is not persisted into the created draft order.

![Screenshot 2024-03-08 at 17 57 07](https://github.com/Shopify/ui-extensions/assets/3954625/7ebe00d0-a66c-4e07-b525-d66d699a0b8b)

## Steps to reproduce the behavior:

1. Create a company, and change the checkout settings > Order submission value to "Submit all orders as drafts for review"
2. Create any Checkout UI Extension that appear on the purchase.* target, then use the "applyAttributeChange" function to update any attribute
3. Confirm that the applyAttributeChange result is success
4. Complete the checkout, see a draft order is being created
5. Notice that the attribute is not persisted to the draft order

## Expected behavior
The value from "applyAttributeChange" should persist into the draft order created by the B2B customer

## Screenshots

![Screenshot 2024-03-08 at 17 57 07](https://github.com/Shopify/ui-extensions/assets/3954625/3b72e432-3fa3-40fe-9d67-fef41a228e74)

https://github.com/Shopify/ui-extensions/assets/3954625/fdc1dfca-79c9-4f90-adc1-3e79bfedf741

**Comment by emelerofik** [comment]
I can confirm this behavior, it happens to us too. The attribute update does not work and neither does the metafield one. It seems that the hook detects the changes, but they are not persisted when processing the order.

**Comment by yesyo** [comment]
Are there any updates on this? We tried using applyAttributeChange with API version 2024-07, but we now receive the error: "applyAttributeChange is not supported on this checkout. Consider checking 'instructions.attributes' first." Is applyAttributeChange just not supported for draft orders, or are we doing something wrong?

**Comment by sjanczy2** [comment]
Attributes are not currently supported on draft orders as per [this documentation](https://shopify.dev/docs/api/checkout-ui-extensions/2024-07/instructions-update#instruction-checking). We plan to remove this limitation in a future update, in which case that instruction will instead `true`. We'll update our documentation when attributes become supported.
