### ISSUE TITLE
[Post-purchase UI] Session token has invalid API key

### ISSUE THREAD

**Issue by SuspenseFallback** [Shopify/ui-extensions#1817]
## Please list the package(s) involved in the issue, and include the version you are using

`@shopify/post-purchase-ui-extensions-react: ^0.13.5`

## Describe the bug

When sending API requests back to my Shopify App backend, I get this error:

```
08:53:56 │ web-backend  │ [shopify-app/INFO] Running validateAuthenticatedSession
08:53:56 │ web-backend  │ [shopify-app/ERROR] Error when loading session from storage: Error: Session token had 
invalid API key
```

and

<img width="428" alt="Screenshot 2024-03-09 at 9 00 43 AM" src="https://github.com/Shopify/ui-extensions/assets/86506971/8c7d6f2f-1f5c-4880-9a02-ddb5cc1e2667">

## Steps to reproduce the behavior:

1. Use this code in a post-purchase extension:

```
// APP_URL and inputData have been defined
const wallet = await fetch(`${APP_URL}/api/create-client-wallet`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${inputData.token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        walletName,
      }),
    })
      .then((response) => response.json())
      .then((response) => console.log(response))
      .catch((err) => {
        console.error(err);
        return error;
      });
```

## Expected behavior

The API successfully returns '200'.

## Screenshots

None.

## Additional context

I'm not very sure how to go about this. Shopify only has documentation for remix backends, so I'm not sure if I'm doing something wrong.

**Comment by dnagoda** [comment]
This doesn't look like a bug.

Looking at your extension code, it looks like you're making an API call to your app backend. Your app backend is parsing the request and not finding the expected `Authorization` header. You should be able to confirm that the fetch request is hitting your backend by looking at your server logs.

One thing to note, depending on how you have your backend setup, there may be endpoints configured with the expectation that the request is coming from the Shopify admin. For security reasons, you do not want to copy the required tokens to be able to make those requests from within and extension. Instead, you should configure a separate authentication method that can be securely called from an extension.

Something that might help with this last part is the [Extension Session Token API](https://shopify.dev/docs/api/checkout-ui-extensions/2024-01/apis/session-token). This would give you a secure way to generate a JWT token that can be validated on your backend server.

Another option that might work for you would be to setup an [App Proxy](https://shopify.dev/docs/apps/online-store/app-proxies).

There are security and compatibility considerations for both extension session tokens and app proxies that are detailed at the bottom of the [Extension Configuration docs in the Network Access section](https://shopify.dev/docs/api/checkout-ui-extensions/2024-01/configuration).
