### ISSUE TITLE
Show or hide Checkout UI Extensions

### ISSUE THREAD

**Issue by SergioMancilla** [Shopify/ui-extensions#1822]
Hi, I'm developing a Shopify app and want to add a panel when users can enable or disable extensions. For example: A option in the panel can be "Show x product in pre-purchase panel", similar as Dropify (https://apps.shopify.com/dropify-5?locale=es&show_store_picker=1). I know I can create extensions to add features to Checkout page, but **how I could to activate/deactivate these extensions from a option?**

**Comment by dnagoda** [comment]
There's not a way to activate/deactivate checkout ui extensions from their associated app. Extensions are placed in the checkout by the merchant.

If you need to pass information, configuration/settings/etc..., from the app to extensions you'll probably do that using metafields. Metafields would be set from the app and later retrieved in the extension.

The [custom field tutorial](https://shopify.dev/docs/apps/checkout/custom/fields) is a good example of how to set metafields from within an extension. Using metafields from within an extension is similar.

Another useful tutorial might be the [pre-purchase offer](https://shopify.dev/docs/apps/checkout/product-offers/pre-purchase/build?framework=react). The high level idea here is that you first create an app, then add extensions to the app. The app can "talk" the extensions be setting metafields that are retrieved by the extensions.
