### ISSUE TITLE
ChoiceList spacing is too large

### ISSUE THREAD

**Issue by bakura10** [Shopify/ui-extensions#1829]
## Please list the package(s) involved in the issue, and include the version you are using

admin-ui-extensions (2024-01)

## Describe the bug

The space between each choice is using a "large" gap, which creates a weird looking form:

<img width="638" alt="image" src="https://github.com/Shopify/ui-extensions/assets/1198915/a060a5f1-a134-4f82-b9bb-588be8f9408a">

The documentation is showing a tighter spacing:

<img width="190" alt="image" src="https://github.com/Shopify/ui-extensions/assets/1198915/3666a685-a7a3-46e0-bc0f-795977f94c76">

Thanks!

**Comment by belalsj** [comment]
Hello @bakura10,

Thanks for bringing this up to our attention. We are working on a fix. You could expect this to be fixed this week.
