### ISSUE TITLE
Customer account UI extension is not showing up (order status)

### ISSUE THREAD

**Issue by Arkan94** [Shopify/ui-extensions#1830]
Customer account UI extension is not showing up (order status)

After I created a new account UI extension in app ID 4918565 according to Shopify documentation
[https://shopify.dev/docs/apps/customer-accounts/build-inline-extensions/order-status?framework=react](https://shopify.dev/docs/apps/customer-accounts/build-inline-extensions/order-status?framework=react)
all required files and folders have been created. I used commands `npm run built` and `npm run deploy` – when opening test page, extension is not affecting the page.

<img width="719" alt="Screenshot 2024-03-18 at 14 26 40" src="https://github.com/Shopify/ui-extensions/assets/16576545/1f249d54-b306-46c3-b21d-09a1f7d0e4f8">

Any console commands that I try to display in the block also do not work.
Two types of blocks were automatically created, with targets `customer-account.order.action.menu-item.render` and `customer-account.page.render` and basic code for it. Both blocks are not displayed on the corresponding pages. The required block was added to the profile page in the theme editing section and a store where developer preview is allowed is also used for testing.

<img width="822" alt="Screenshot 2024-03-18 at 12 59 25" src="https://github.com/Shopify/ui-extensions/assets/16576545/89dd8483-9357-4c12-a8b9-e42c2d9e3c63">
<img width="748" alt="Screenshot 2024-03-18 at 12 59 30" src="https://github.com/Shopify/ui-extensions/assets/16576545/3f428872-08e1-4cc5-badd-a55f3f778292">
<img width="1331" alt="Screenshot 2024-03-18 at 14 00 53" src="https://github.com/Shopify/ui-extensions/assets/16576545/7eee87b7-5246-4c95-ae3f-851d687a40ad">
<img width="708" alt="Screenshot 2024-03-18 at 13 44 52" src="https://github.com/Shopify/ui-extensions/assets/16576545/b1365576-0ea1-4669-8482-aa836a1009f3">

Package version:
    "@shopify/app": "^3.57.1",
    "@shopify/cli": "^3.57.1",
    "@shopify/ui-extensions": "^2024.1.1",
    "@shopify/ui-extensions-react": "^2024.1.1",

Steps to reproduce:
1) Create customer UI extension  according to Shopify documentation [https://shopify.dev/docs/apps/customer-accounts/build-inline-extensions/order-status?framework=react](https://shopify.dev/docs/apps/customer-accounts/build-inline-extensions/order-status?framework=react)
2) run `npm run built` command
3) run `npm run deploy` command
4) visit customer orders page  (/account/orders) in new customer accounts

**Comment by Arkan94** [comment]
Hi @brianshen1990 , thank you for your answer, I have created a new extension in my developer store (customer-account-extensions.myshopify.com) according to the above mentioned documentation and after executing the `npm run dev` command my preview worked.
<img width="1201" alt="Screenshot 2024-03-20 at 13 38 51" src="https://github.com/Shopify/ui-extensions/assets/16576545/6498f2c7-800a-4122-9113-a534d39b2dcf">

But when executed `npm run build` and `npm run deploy` commands, nothing happened (extension does not work / show up). Summary, when i use `npm run dev` command extension is working but after deployment – no.
<img width="1271" alt="Screenshot 2024-03-20 at 13 42 22" src="https://github.com/Shopify/ui-extensions/assets/16576545/f4e5e751-65d5-488c-9066-3d83b8db3c72">

**Comment by brianshen1990** [comment]
Hey @Arkan94 , got it~~
Customer account UI extension is in preview at the moment, we only support `npm run dev` to preview locally. For customer account ui extension deployment and activation, please wait for GA https://shopify.dev/docs/apps/customer-accounts#release-timeline~

**Comment by oluwatimio** [comment]
Closing this issue as per @brianshen1990 answer https://github.com/Shopify/ui-extensions/issues/1830#issuecomment-2012202319 here.
