### ISSUE TITLE
Debugging logs or errors are not showing

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/ui-extensions#1833]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/app": "3.57.0",
"@shopify/cli": "3.57.0"

"@shopify/shopify_function": "0.1.0",

## Describe the bug

The log & error doesn't show

## Steps to reproduce the behavior:

1. Generate delivery customization
2.Modify
3. Build & Deploy

## Expected behavior

Can see the log, error to validate business works

## Screenshots

<img width="697" alt="image" src="https://github.com/Shopify/ui-extensions/assets/16915274/91513c40-51f4-472d-bf53-d9cb4282e17a">
<img width="1056" alt="image" src="https://github.com/Shopify/ui-extensions/assets/16915274/444401f4-3c29-4df8-a43d-a1bba165b9ec">

## Additional context

Initial app without remix

**Comment by dnagoda** [comment]
Hi @hoannguyen02 👋 

Here's the documentation for how Functions handle/report errors:

https://shopify.dev/docs/api/functions/errors#how-it-works

Console logs/errors should be captured, but only if the Function fails while running. Successful runs will not capture the associated logs.

**Comment by hoannguyen02** [comment]
hi @dnagoda 

Many thanks for the response.

Could you show me example code? at the moment I made 2 type of errors but cannot click any of them to see details.

<img width="1097" alt="image" src="https://github.com/Shopify/ui-extensions/assets/16915274/2f917f6e-bdfb-4405-88ae-a0855eb55ccf">

**Comment by dnagoda** [comment]
@hoannguyen02 I'm going to dig a little deeper into this. Is this a development store that you're testing on?

**Comment by hoannguyen02** [comment]
hi @dnagoda it is shopify plus store, not development store

**Comment by hoannguyen02** [comment]
Thank you @dnagoda
