### ISSUE TITLE
UI extension not showing on Thank You page

### ISSUE THREAD

**Issue by julianozapiet** [Shopify/ui-extensions#1842]
## Please list the package(s) involved in the issue, and include the version you are using
- ui-extensions v2023.10.x
- ui-extensions-react v2023.10.x

## Describe the bug

After deploying the checkout extensions and adding the block in the Thank you page via checkout editor, the extension shows just fine in the editor preview, but it does not render at all on the actual Thank you page of the store, when an order is placed.

If the extension is also exported to the order status page, it will show correctly on both checkout editor and on the real order status page.

## Steps to reproduce the behavior:

1. Add extension on the Thank you page via checkout editor.
2. Verify that the extension is rendered in the editor preview.

## Expected behavior

Extension should render on the real Thank you page when an order is created

## Screenshots

![image](https://github.com/Shopify/ui-extensions/assets/72195704/c9fcfeed-5c1d-4e8e-bcd1-13968fdfed47)
![image](https://github.com/Shopify/ui-extensions/assets/72195704/f487df54-4d72-4429-8319-590eba674aa6)

## Additional context

I've tried on different themes/stores/fresh installs of the app but the problem persists.

**Comment by julianozapiet** [comment]
Hey @dnagoda thanks for getting back!

> Are you using the purchase.thank-you.block.render target?

Yes, this is on my shopify.extension.toml file:
```
[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/Checkout.tsx"
```

And this is how i export it in Checkout.tsx:
```
function Confirmation() {
    return <Text>Lorem ipsum dolor sit amet</Text>;
}

export const thankYouBlock = reactExtension('purchase.thank-you.block.render', () => <Confirmation />);
```

>Can you please provide the URL you're seeing for the thank-you page where the extension is not displayed?

This is one example: `https://juliano-checkout-2.myshopify.com/checkouts/do/cea7b95d701d2e682c3c99bd160b1ac0/thank-you`

>you've enabled extensibility for the thank-you page in the shops admin Settings / Checkout area?

Yes, this is how it looks like:
![image](https://github.com/Shopify/ui-extensions/assets/72195704/8a0ec152-b0c7-4201-87b5-89611976fbd3)

**Comment by dnagoda** [comment]
Thanks.

This looks like a Draft Order based on the URL you provided. Unfortunately, extensibility is not fully supported on draft orders. We're working on it, but there's no public ETA yet.

**Comment by julianozapiet** [comment]
Thanks for explaining @dnagoda
