### ISSUE TITLE
Missing type `orderConfirmation` in useAPI

### ISSUE THREAD

**Issue by Rafi993** [Shopify/ui-extensions#1901]
## Please list the package(s) involved in the issue, and include the version you are using

    "@shopify/ui-extensions": "2024.4.x",
    "@shopify/ui-extensions-react": "2024.4.x"

## Describe the bug

Value `orderConfirmation` is present in `useAPI` but it is missing typescript type

## Steps to reproduce the behavior:

1. Add `useAPI` to thank you extension
1. access `orderConfirmation` from `useAPI`
1. It will have the value but it will be missing type

## Expected behavior

1. Type should be added for `orderConfirmation` in `useAPI`

**Comment by edgardcooper-thomasdhondt** [comment]
Use it like this:

```const { orderConfirmation } = useApi("purchase.thank-you.block.render");```
