### ISSUE TITLE
POS UI Extensions - Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by adamwooding** [Shopify/ui-extensions#1906]
## Please list the package(s) involved in the issue, and include the version you are using

```
"react": "^17.0.0",
"@shopify/retail-ui-extensions-react": "1.7.0"
```
## Describe the bug

We've just updated our POS Cafe to the latest version of the retail UI extensions package:

`"@shopify/retail-ui-extensions-react": "1.7.0"`

and we are now getting the following error message:

`Invalid hook call. Hooks can only be called inside of the body of a function component`

![devrex_0-1713767986658](https://github.com/Shopify/ui-extensions/assets/1168874/2cead20f-2ee7-46d6-9cc2-b73eeff433b0)

We've also created a brand new app and extension, and still getting the same error.

We then tried commenting out the useExtensionAPI() and the tile works:

![devrex_1-1713768101066](https://github.com/Shopify/ui-extensions/assets/1168874/1ee0f58f-c7ad-4765-8c66-128497495d3a)

This is the package.json of POS extension:

```
{
  "name": "pos-ui",
  "private": true,
  "version": "1.0.0",
  "main": "dist/main.js",
  "license": "UNLICENSED",
  "dependencies": {
    "react": "^17.0.0",
    "@shopify/retail-ui-extensions-react": "1.7.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0"
  }
}
```

We are wondering if there is an issue with the useExtensionApi() hook. 

Any assistance would be greatly appreciated.

Thank you so much for your time,
Adam Wooding

**Comment by js-goupil** [comment]
We did encounter this when we were tinkering a while back. Turns out it was a developer error when they were calling the `render` function. 

Invalid:
```
render('pos.home.tile.render', SmartGridTile)
```

Valid:
```
render('pos.home.tile.render', () => <SmartGridTile />)
```

Could you get them to double check the syntax of that function call?

**Comment by brandonkhj** [comment]
Hi, I am facing the same issue with a fresh new app + sample code from Shopify generated POS UI extension. Any update on this? @js-goupil

**Comment by adamwooding** [comment]
Hey @brandonkhj & @js-goupil , we just updated our CLI to v3.60 which was just released, and this seems to have resolved the issue. Can you check which version of the CLI you're using?

**Comment by brandonkhj** [comment]
hey @adamwooding , Thanks lot! it's working for me now with latest CLI version :)
