### ISSUE TITLE
Adding images under cart: Checkout Ui Extension

### ISSUE THREAD

**Issue by ksyp-7** [Shopify/ui-extensions#1962]
## Question

is it possible to add images in schema-2 of checkout, under cart products?

## Screenshots
![Screen Shot 2024-05-13 at 1 16 28 PM](https://github.com/Shopify/ui-extensions/assets/44991093/3cf1de43-bc6e-4cd0-858e-6f9ab5ec36b0)

**Comment by jun-shop** [comment]
👋 hi please don't add the "bug" label unless you are really describing a bug.
You can find out more about extension targets for checkout here: https://shopify.dev/docs/api/checkout-ui-extensions/2024-04/extension-targets-overview#checkout-locations-order-summary
As well as the image component here: https://shopify.dev/docs/api/checkout-ui-extensions/2024-04/components/media/image

Currently you cannot bundle static assets like images with your checkout UI extension, and we recommend that you host your image on a CDN

**Comment by ksyp-7** [comment]
Thanks for reply!
