### ISSUE TITLE
Text emphasis="bold" doesnt work on Firefox

### ISSUE THREAD

**Issue by sov-brandstaetter** [Shopify/ui-extensions#2003]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/ui-extensions-react": "2024.4.1"

## Describe the bug

When using <Text emphasis="bold">Some Text</Text> the text has a font-weight of 500. On chrome this looks bold but on firefox it looks the same as regular text

## Steps to reproduce the behavior:

```
import { Text } from "@shopify/ui-extensions-react/checkout";
<Text emphasis="bold">Some Text</Text>
```

## Expected behavior

The text should be bold on firefox as well

## Screenshots
On Chrome it works:
![grafik](https://github.com/Shopify/ui-extensions/assets/145344238/ed6418e4-8d30-4ecf-acbf-83e344fec2cf)

On Firefox it doesnt:
![grafik](https://github.com/Shopify/ui-extensions/assets/145344238/6779b493-078c-4201-9758-3cabc94ac1e1)

**Comment by simontaisne** [comment]
Hey @sov-brandstaetter, could you share your Firefox version? I wasn't able to reproduce the issue on the latest `126.0` version.

**Comment by simontaisne** [comment]
The issue should now be fixed 👍 Let us know if you're still seeing anything off.

**Comment by sov-brandstaetter** [comment]
Amazing it works now 👍
