### ISSUE TITLE
useShippingAddress stopped working on the Thank You page

### ISSUE THREAD

**Issue by julien-mamalian** [Shopify/ui-extensions#2058]
## Please list the package(s) involved in the issue, and include the version you are using
"@shopify/ui-extensions": "2024.4.x",
"@shopify/ui-extensions-react": "2024.4.x",
"react": "^18.0.0",

## Describe the bug

useShippingAddress(); in the "purchase.thank-you.block.render" extension target stopped working. It was working both on the live extension and locally but stopped working yesterday. shippingAddress returns _undefined_ as well. I did not change anything and I have access to customer data.

## Expected behavior

useShippingAddress should return the order shipping address

**Comment by mkupiniak** [comment]
Same issue here. Stopped working (returns `undefined`) out of nowhere, without changing anything else.

**Comment by mkupiniak** [comment]
Might be related: https://github.com/Shopify/ui-extensions/issues/1378

**Comment by yosef-grant** [comment]
Same thing happened to me. It worked perfectly until Friday 7 June, now I get no value for useShippingAddress. Interestingly useBillingAddress has the same issue - returns undefined, but useEmail() returns the proper value as expected. Furthermore if you have extensions on the 3-page checkout that utilise the shipping address API, they all work as normal but once you hit the thank you page they report errors stating no address can be found. It seems to be an issue rooted on the Thank You page.

**Comment by MathiasGr** [comment]
Same here. Did anyone find a remediation?

**Comment by jamesvidler** [comment]
Thank you for reporting this issue. We have reproduced it and are investigating.

**Comment by MathiasGr** [comment]
Any news or ETA on a fix to communicate? This completely broke our app @jamesvidler

**Comment by jamesvidler** [comment]
This issue has just been resolved. Can you please verify the `shippingAddress` is now returning the expected value?

**Comment by tomk1v** [comment]
@jamesvidler also confirms, it now works!

**Comment by mkupiniak** [comment]
Works fine, thank you for the quick fix! 🙌🏻

**Comment by mdanielsson** [comment]
We also still see what we suspect is this issue. The useBillingAddress returns undefined. @jamesvidler
