### ISSUE TITLE
orderConfirmation.id is always undefined

### ISSUE THREAD

**Issue by edhgoose** [Shopify/ui-extensions#2064]
## Please list the package(s) involved in the issue, and include the version you are using

        "@shopify/ui-extensions": "2024.1.x",
        "@shopify/ui-extensions-react": "2024.1.x"
        "@shopify/app": "^3.58.2",
        "@shopify/cli": "^3.60.1"

## Describe the bug

We are using a ThankYou page extension and require access to the Order ID. 

On https://shopify.dev/docs/apps/build/checkout/thank-you-order-status, the documentation states:

> Note that for extensions on the Thank you page (target purchase.thank-you), the order is not yet created when these extensions are displayed. However, the order id is available. You can use [OrderConfirmationApi](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/order#orderconfirmationapi) to obtain the order [confirmation number](https://help.shopify.com/en/manual/orders/status-tracking/confirmation-numbers), or the order id. Use the order id to uniquely identify the order, and to fetch additional information about the order using the GraphQL API after order creation is complete.

Using https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/order#orderconfirmationapi we have introduced code similar to the example.

Unfortunately, we find while the `orderConfirmation` object is set, the `id` is always undefined.

Our code:

```
import {
	reactExtension,
	useApi,
} from "@shopify/ui-extensions-react/checkout";

import { useEffect, useState } from "react";

function Extension() {
	const { orderConfirmation } = useApi();

	if (!orderConfirmation) {
		console.log("orderConfirmation missing");
		return null;
	}

        // This will be set.
	console.log("orderConfirmation", orderConfirmation);
        
        // This will always be undefined
	console.log("orderConfirmation.id", orderConfirmation.id);

	return null;
}


export default reactExtension(
	"purchase.thank-you.block.render",
	() => <Extension />,
);
```

## Steps to reproduce the behavior:

1. Make an extension using the React code in the example above.
1. Make a test purchase. It may be relevant that we're using the bogus gateway.
1. Confirm that console.log does not have a value for the order confirmation.

## Expected behavior

An order confirmation ID.

## Screenshots

![CleanShot 2024-06-11 at 17 02 13@2x](https://github.com/Shopify/ui-extensions/assets/1108173/06584189-8386-4b5c-ad84-9b9c335e8646)

**Comment by jamesvidler** [comment]
@edhgoose the `orderConfirmation` is a subscribable value, so you'll need to access it a different way:
```
const { orderConfirmation } = useApi();
const { id } = useSubscription(orderConfirmation);

//... or
let id = null;
orderConfirmation.subscribe((value) => {
  id = value
});
```

Looks like our code example in the [docs](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/order#orderconfirmationapi) may have this wrong. Thanks for pointing this out.

**Comment by edhgoose** [comment]
Thanks for the reply @jamesvidler - that seems to be it.

Am I correct in assuming wherever I see `StatefulRemoteSubscribable`, I should use this approach?

**Comment by edhgoose** [comment]
Can you also confirm how to type it correctly?

I'd have assumed `OrderConfirmation` was the right type, but I can't seem to see it in my packages.

**Comment by edhgoose** [comment]
Thanks @jamesvidler - I appreciate it. I'll double check my types and confirm if that fixes that issue.

I've found a similar problem https://github.com/Shopify/ui-extensions/issues/2068, but if I've understood you correctly it looks to be a coincidence.

Can you help and confirm?

**Comment by edhgoose** [comment]
> I believe this type was introduced in 2024.4.x, so you may not have access to the type in your current version.

Can confirm the types are in 2024.4. Thanks for that titbit.

**Comment by edhgoose** [comment]
Hey @jamesvidler - just want to check, will the docs be updated?

I'm not sure on your process here so wanted to double check if closing was correct.

Thanks!

**Comment by jamesvidler** [comment]
Yes, we are going to update the docs.

**Comment by williamoconnorme** [comment]
If I should create a new issue let me know but I'm seeing a similar issue when using the 2024.07.x package versions. I've tried the example above and from the docs site and it appears that orderConfirmation never updates after subscribing.

Using a development store with developer preview: Checkout and Customer Accounts Extensibility. Could there be any nuance in development stores vs production?

My configuration:

```
"@shopify/ui-extensions": "2024.07.x",
"@shopify/ui-extensions-react": "2024.07.x",
"react": "^18.0.0"
```

```
import {
  reactExtension,
  Banner,
  useApi,
  useSubscription,
} from '@shopify/ui-extensions-react/checkout';

export default reactExtension(
  'purchase.thank-you.block.render',
  () => <Extension />,
);

function Extension() {
  const { orderConfirmation } = useApi();
  const { id } = useSubscription(orderConfirmation);

  if (id) {
    return (
      <Banner>
        Please include your order confirmation ID
        ({id}) in support requests
      </Banner>
    );
  }

  return null;
}
```

**Comment by williamoconnorme** [comment]
Managed to resolve my issue. I needed to pass the extension target as an argument

```
import {
  reactExtension,
  Banner,
  useApi,
  useSubscription,
} from '@shopify/ui-extensions-react/checkout';

export default reactExtension(
  'purchase.thank-you.block.render',
  () => <Extension />,
);

function Extension() {
  const { orderConfirmation } = useApi<"purchase.thank-you.block.render">();
  const { order } = useSubscription(orderConfirmation);

  if (order.id) {
    return (
      <Banner>
        Please include your order confirmation ID
        ({order.id}) in support requests
      </Banner>
    );
  }

  return null;
}
```
