### ISSUE TITLE
[Docs script] Incorrect props on shopify.dev for text component

### ISSUE THREAD

**Issue by owenanderson** [Shopify/ui-extensions#208]
## Package

`post-purchase-ui-extensions`

## Describe the bug

The [post-purchase](https://shopify.dev/api/checkout-extensions/components/text) Text and TextBlock components have the incorrect size props on shopify.dev docs.

## Expected behavior

Props for size component should be `"extraSmall" | "small" | "base" | "large" | "extraLarge"` not `"auto" | "fill" | number`

## Screenshots

<img width="1733" alt="Screen Shot 2021-08-25 at 12 36 32 PM" src="https://user-images.githubusercontent.com/16530735/130853802-d964e871-5ee8-44bf-8f8a-33ff970d729c.png">

**Comment by cdarland** [comment]
Closing this issue as the source of the problem has been resolved. A future publish of the `post-purchase-ui-extensions` package should resolve the docs issue.
