### ISSUE TITLE
address2 field not updating when using applyShippingAddressChange method for Costa Rica

### ISSUE THREAD

**Issue by HasanArmstrong** [Shopify/ui-extensions#2083]
## Please list the package(s) involved in the issue, and include the version you are using

"react": "^18.0.0",
"@shopify/ui-extensions": "2024.4.x",
"@shopify/ui-extensions-react": "2024.4.x"

## Describe the bug

When selecting Costa Rica in the country dropdown (other countries it works), the address2 field on checkout is not updating when using [applyShippingAddressChange ](https://shopify.dev/docs/api/checkout-ui-extensions/2024-04/apis/addresses#checkoutapi-propertydetail-applyshippingaddresschange)method to update the shipping address inputs value however it returns a successful response and no error messages. The other fields (address1, zip, city, provinceCode) are being updated successfully. 

## Steps to reproduce the behavior:

1. Select Costa Rica in country dropdown
2. Use [applyShippingAddressChange ](https://shopify.dev/docs/api/checkout-ui-extensions/2024-04/apis/addresses#checkoutapi-propertydetail-applyshippingaddresschange) method to update address2 field  value on checkout
1. Notice the address2 field is not updating

## Expected behavior

Expect the address2 field value to be updated with the value from [applyShippingAddressChange ](https://shopify.dev/docs/api/checkout-ui-extensions/2024-04/apis/addresses#checkoutapi-propertydetail-applyshippingaddresschange) for Costa Rica

## Screenshots

<img width="432" alt="Screenshot 2024-06-14 at 11 50 13 AM" src="https://github.com/Shopify/ui-extensions/assets/19598402/03ccb879-4016-437c-8783-62a4fd45f902">

<img width="463" alt="Screenshot 2024-06-14 at 11 56 51 AM" src="https://github.com/Shopify/ui-extensions/assets/19598402/a7a6faf5-5683-4309-a432-055b2d05f088">

**Comment by jsia18** [comment]
This also happens to me even after updating address2 field, it does not get updated same with other countries in my case Philippines

**Comment by jamesvidler** [comment]
This issue has been resolved. Can you confirm you are no longer experiencing it?

**Comment by jsia18** [comment]
I can confirm on my end that it was resolved

**Comment by jamesvidler** [comment]
@HasanArmstrong feel free to re-open this issue if you continue to experience any issues.
