### ISSUE TITLE
[Account Extensions] Display properties not working in Account section

### ISSUE THREAD

**Issue by kpeatt** [Shopify/ui-extensions#2158]
## Please list the package(s) involved in the issue, and include the version you are using

```
    "@shopify/ui-extensions": "unstable",
    "@shopify/ui-extensions-react": "unstable"
```

## Describe the bug

Despite being listed in the types and API, display properties don't work on full page extensions in the New Customer Account area.

## Steps to reproduce the behavior:

1. Add a `<View>` component with `display='none'` and some children to a full page extension in the new customer account area.
1. See that the view renders.

## Expected behavior

The view does not render.

## Additional context

The new display properties seem to be working fine in checkout blocks when rendered in the checkout. I haven't tried the order status pages.

**Comment by renerbaffa** [comment]
hey @kpeatt, thanks for reporting this!
Let me have a look and get back to you soon

**Comment by renerbaffa** [comment]
@kpeatt we will release a new version with support for all the options of `display` later today or tomorrow. I can let you know when that is rolled out if you want
