### ISSUE TITLE
[Admin Extension UI] Order Index AdminAction modal button won't open Shopify Admin links

### ISSUE THREAD

**Issue by Alrz-a** [Shopify/ui-extensions#2177]
## Project Dependencies:
+ @shopify/ui-extensions: ^2024.7.0
+ ui-extensions-react: ^2024.7.0
+ react": 18.3.1

Action target: `admin.order-index.selection-action.render`

## Describe the bug

Primary and secondary buttons the `AdminAction` component do not open links to Admin Panel Order page. After clicking the button, a download dialogue is opened. Other URLs seem to open with no issue. 
Below is the `AdminAction` component
```
<AdminAction
            title="title"
            primaryAction={
                <Button
                    to="/orders/5199742501072"
                    target="_blank"
                    download={false}
                >
                    Link
                </Button>
            }
        >
    <ActionComponent />
</AdminAction>
```

## Steps to reproduce the behavior:

1. Create Admin Action for order index page.
2. Add a primary action to the `AdminAction` component with the `to/href` prop set to an order detail page in Admin Panel

## Expected behavior
Page relating to the URL should be opened.

**Comment by cupnoodle** [comment]
This applies to all targets, any Admin Action's primary and secondary button, they will automatically download file if the target href is set to Shopify Admin links, either using HTTP or Admin protocol format

**Comment by MitchLillie** [comment]
Hi! This should now be fixed--no ui-extensions update required. Let us know if you have any other issues.
