### ISSUE TITLE
customer-account: ImageGroup extra blank space

### ISSUE THREAD

**Issue by mateusvahl** [Shopify/ui-extensions#2321]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/ui-extensions (unstable)
@shopify/ui-extensions-react (unstable)

## Describe the bug

`<ImageGroup />` seems to be always creating space for three items, even if you have one or two images, example:

```tsx
<ImageGroup variant="inline-stack" totalItems={1}>
  <Image source="https://cdn.shopify.com/your_image.jpg" />
</ImageGroup>
```

This can be fixed by wrapping the content into View+maxInlineSize, but can be cumbersome with dynamic content, where one item is `44`, two `58` and three or more being `88`

```tsx
<View maxInlineSize={45}>
  <ImageGroup variant="inline-stack" totalItems={1}>
    <Image source="https://cdn.shopify.com/your_image.jpg" />
  </ImageGroup>
</View>
```

Result:

![Image](https://github.com/user-attachments/assets/1029d25c-01cd-4b94-9b49-ab7f3c7a56d3)

## Expected behavior

Should only allocate the necessary space.

## Additional context

Please let me know if this isn't the right place for  `@shopify/ui-extensions`.

**Comment by sylvhama** [comment]
Hello there, 

I have just deployed a fix. Please feel free to re-open the ticket if you encounter any further problems with that component. 

Thank you!
