### ISSUE TITLE
Storefront API's product onlineStoreUrl returns null

### ISSUE THREAD

**Issue by kylebuildsstuff** [Shopify/ui-extensions#2355]
## Please list the package(s) involved in the issue, and include the version you are using

api_version = "2024-07"

"@shopify/app": "^3.58.2",
    "@shopify/cli": "^3.66.1",
    "@shopify/shopify_function": "0.0.3",
    "@shopify/ui-extensions": "2024.7.0",
    "@shopify/ui-extensions-react": "2024.7.0",

## Describe the bug

When using the Storefront API from a checkout extension to fetch a product's `onlineStoreUrl` the field returns null.

## Steps to reproduce the behavior:

1. Create checkout extension
2. Fetch product's `onlineStoreUrl` field using the Storefront API

## Expected behavior

The Storefront API should return the url for the product when `onlineStoreUrl` is included.

## Additional context

It seems to be an ongoing issue, judging from responses in this thread:

https://community.shopify.com/c/hydrogen-headless-and-storefront/why-do-outputted-null-on-the-onlinestoreurl-field-in-the-product/td-p/1399325

**Comment by kirakik** [comment]
This is because you're testing on a password-protected store, and development stores are always password protected. In production stores, it will not be null.
