### ISSUE TITLE
TextField does not apply maxLength restriction when type is set to number

### ISSUE THREAD

**Issue by PhiloNL** [Shopify/ui-extensions#2357]
When using `@shopify/ui-extensions/checkout` and the `TextField` component the maxLength is not applied when the type is set to `number`.

## Steps to reproduce the behavior:
Create a text field and enter a few characters.

```
root.createComponent(TextField, {
    label: 'Number',
    maxLength: 2,
    type: 'number',
    required: true,
});
```

## Expected behavior

The field should not allow more than 2 characters.

**Comment by jun-shop** [comment]
👋 hi there - I believe it's expected that `maxLength` does not apply to type `number` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength. We can add a note in our docs to make this more clear
