### ISSUE TITLE
Regression: Modal has unnecessary bottom padding

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/ui-extensions#2365]
## Please list the package(s) involved in the issue, and include the version you are using

    "@shopify/ui-extensions": "2024.7.0",
    "@shopify/ui-extensions-react": "2024.7.0",

## Describe the bug

In last days, our modals started getting unnecessary bottom padding

## Steps to reproduce the behavior:

```tsx
            <Link
              overlay={
                <Modal id="my-modal" title="Return policy">
                  <TextBlock>
                    We have a 30-day return policy, which means you have 30 days after receiving
                    your item to request a return.
                  </TextBlock>
                  <TextBlock>
                    To be eligible for a return, your item must be in the same condition that you
                    received it, unworn or unused, with tags, and in its original packaging. You’ll
                    also need the receipt or proof of purchase.
                  </TextBlock>
                </Modal>
              }
            >
              Return policy
            </Link>
```

## Expected behavior

No bottom padding should exist in modal

## Screenshots

![Image](https://github.com/user-attachments/assets/312ee089-1749-40c0-8528-8b1806455dee)

## Additional context

Side note: modal title and "X" button also got padding in last month or so, not sure if this was intended or not, but I'm not a fan of this, it looks bit off when modal has no padding

**Comment by oliverigor** [comment]
@patryk-smc @jeanffc, should be fixed now.
