### ISSUE TITLE
Map within modal has height of 0px when used with "fill"

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/ui-extensions#2377]
## Please list the package(s) involved in the issue, and include the version you are using

```
    "@shopify/ui-extensions": "2024.7.0",
    "@shopify/ui-extensions-react": "2024.7.0",
```

## Describe the bug

When using Map component in Modal, with `minBlockSize="fill"`, the Map component height is exactly 0 px. 

## Steps to reproduce the behavior:

```tsx
function MapExample() {
  return (
    <>
      <Link
        overlay={
          <Modal id="test-modal">
            <Map
              latitude={40.74}
              longitude={-73.98}
              accessibilityLabel="Map"
              minBlockSize={"fill"}
            />
          </Modal>
        }
      >
        Open map
      </Link>
    </>
  )
}
```

## Expected behavior

The Map component should take full space of Modal.

## Screenshots
![Image](https://github.com/user-attachments/assets/557a5aa1-3eca-4ebe-8b0f-d057ace90c15)

## Additional context

Without this working it seems impossible to properly embed map on all screens, without scroll bars or other issues.

**Comment by oliverigor** [comment]
But in the case above, you can use size="max" for modal and minBlockSiz="fill" for modal, it should work as the Map will have a "defined" height to grow :D
