### ISSUE TITLE
POS UI Extensions - Extension is not Full Screen as Expected

### ISSUE THREAD

**Issue by xqwtsz** [Shopify/ui-extensions#2414]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/ui-extensions": "2024.10.x",
"@shopify/ui-extensions-react": "2024.10.x"
```

Also

```
api_version = "2024-10"
```

in the `shopify.extension.toml`

## Describe the bug

The `Modal` component that is with the target:

```
export default reactExtension('pos.home.modal.render', () => {
  return <Modal />
})
```

is rendering as a modal, and is NOT full screen as expected.

## Steps to reproduce the behavior:

1. Create a fresh POS UI Extension
2. Change the `api_version` in the `shopify.extension.toml` to `2024-07`
3. Run `npm run  dev`, everything is full screen, as expected.
4. Change the `api_version` in the `shopify.extension.toml` to `2024-10`
5. Run `npm run  dev`, modals look like modals and are not full screen.

## Expected behavior

Expect the Modal to be full screen.

### `shopify.extension.toml` - API Version - 2024-07 - Expected

![Image](https://github.com/user-attachments/assets/9f5448ac-38c4-412d-b168-36babf0dac5e)

### `shopify.extension.toml` - API Version - 2024-10 - Broken

![Image](https://github.com/user-attachments/assets/d555536d-e3f8-4d7a-b220-c96f6a02c46e)

**Comment by xqwtsz** [comment]
@js-goupil after 1.5 months you just replied with what I already wrote and no other info.

Is there any plans to make it optional/property? It's a huge change in terms of screen real estate and the current extensions were not created to fit inside small modals in the first place. and why would they be? There was no sign of a change like this coming. 

Upgrading to use the latest version will now require a lot of effort just to try and make things fit, not to mention the user feedback after everything is HALF THE WIDTH.

And it doesn't really matter if its full screen on android, unless you're buying us all new android tablets for all of our POS locations??

**Comment by xqwtsz** [comment]
moved to the forums

**Comment by mdriess** [comment]
We're super disappointed about this update as well to be honest. This is a much worse experience for both developers and merchants when working with extensions. I can't think of a single use case where we'd say 'we're glad we have less screen real estate now'

Not to mention, Android tablets behave differently.
