### ISSUE TITLE
customer account ui: Modal with no actions are showing separator line

### ISSUE THREAD

**Issue by mateusvahl** [Shopify/ui-extensions#2437]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/ui-extensions": "2024.10.x",
"@shopify/ui-extensions-react": "2024.10.x",
```

## Describe the bug

Noticed recently that modals now have `primaryAction` and `secondaryAction` props(great!), however, if the modal is not using those properties the separator line is still showing:

![Image](https://github.com/user-attachments/assets/4d994746-4f70-49b8-a538-bb6c3645b523)

This makes our current modals that are not using `primaryAction` and `secondaryAction` a  bit odd:

![Image](https://github.com/user-attachments/assets/d257dbc0-0ec5-4fd8-891e-49f63c7a4d95)

## Expected behavior

Not show separator line when no actions are provided.

**Comment by mateusvahl** [comment]
Side note: This makes hard to compose when you wan't to render a `<Form />` with submit button:

Before:
```tsx
<Modal>
  <Form onSubmit={...}>
    <Button accessibilityRole="submit">Ok</Button>
  </Form>
</Modal>
```

Now: Buttons are placed outside the `<Form />` and no longer can submit the form(Probably less accessible too?)
```tsx
<Modal primaryAction={<Button onPress={...}>Ok</Button>}>
  <Form>
      still a form? Can we submit 
  </Form>
</Modal>
```

![Image](https://github.com/user-attachments/assets/9361218b-7680-47b7-9a41-a18d2b68f986)

**Comment by brianshen1990** [comment]
Hey @mateusvahl , a fix has been applied to all versions, please have another test, thanks very much!
![Image](https://github.com/user-attachments/assets/d9b52382-50c8-4961-adc7-f7e81c565e08)
