### ISSUE TITLE
customer account ui extensions: Modal title not re-rendering

### ISSUE THREAD

**Issue by mateusvahl** [Shopify/ui-extensions#2446]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/ui-extensions": "2024.10.x",
"@shopify/ui-extensions-react": "2024.10.x",
```

## Describe the bug

In the following code, we are rendering a different `overlay` based a  `status: 'success' | 'error' | undefined` state:

```tsx
 overlay={status === 'success' ? SuccessModal : status === 'error' ? ErrorModal : RegularModal}
```

It seems that the component **_partially_** re-render, but we still see the old modal title.

```tsx
import { BlockStack, Button, Modal, Text, useApi } from '@shopify/ui-extensions-react/customer-account';
import { useState } from 'react';

export const Action = () => {
  const { ui } = useApi();
  const [status, setStatus] = useState<'success' | 'error' | undefined>();
  const MODAL_ID = 'modal-unskip-subscription';

  const onSubmit = () => {
    setStatus('success');
  };

  const handleCloseModal = () => {
    ui.overlay.close(MODAL_ID);
  };

  const RegularModal = (
    <Modal id={MODAL_ID} padding title="Main title">
      <BlockStack spacing="base">
        <Text>Are you sure?</Text>

        <Button onPress={onSubmit}>yes</Button>
        <Button kind="secondary" onPress={handleCloseModal}>
          Cancel
        </Button>
      </BlockStack>
    </Modal>
  );

  const SuccessModal = (
    <Modal id={MODAL_ID} padding>
      <Button onPress={handleCloseModal}>Success, close</Button>
    </Modal>
  );

  const ErrorModal = (
    <Modal id={MODAL_ID} padding>
      <Button onPress={handleCloseModal}>Error, close</Button>
    </Modal>
  );

  return (
    <Button
      kind="secondary"
      overlay={status === 'success' ? SuccessModal : status === 'error' ? ErrorModal : RegularModal}
    >
      My action
    </Button>
  );
};
```

## Screenshots

In this video, you can see that the `SuccessModal` is shown, however, it still is showing the `title` from `RegularModal`

https://github.com/user-attachments/assets/e35efe5b-980f-4de2-9e87-087215963b1f

**Comment by mateusvahl** [comment]
@brianshen1990 We are using this in `"customer-account.page.render"`.

Normally or modals are placed under a `<Page primaryAction={...} />` or `<ResourceItem action={modal} />`, however its seems randomly.

I could try provide a full working environment, but that may take a bit more time.... 

( I think we could place a different `key` on each one as temporary solution )

Thanks.

**Comment by brianshen1990** [comment]
Hi @mateusvahl, thank you! If you want to display a success or error message, I recommend the following approach:

1. Use a form within a modal. 
2. If an error occurs, switch the modal content to display the error information.
3. Upon success, consider [showing a toast](https://shopify.dev/docs/api/customer-account-ui-extensions/2024-10/apis/ui#standardapi-propertydetail-ui) instead of a success modal.

This is the pattern we use in the Customer Account Web.

**Comment by renerbaffa** [comment]
did it work out afterwards @mateusvahl? I'll close this issue for now, but feel free to reopen it if you are still facing any issues
