### ISSUE TITLE
useCheckoutToken hook not return a token

### ISSUE THREAD

**Issue by hashcott** [Shopify/ui-extensions#2466]
## Please list the package(s) involved in the issue, and include the version you are using

```
    "@shopify/ui-extensions": "2024.1.x",
    "@shopify/ui-extensions-react": "2024.1.x",
```
## Describe the bug
I have already defined const `checkoutToken = useCheckoutToken();` on the screen `customer-account.order-status.block.render`, but for some reason, the token cannot be received. Is there a solution to fix this issue?

## Steps to reproduce the behavior:

1. checkout 
2. order status screen

## Expected behavior

`useCheckoutToken` returns an undefined token.

**Comment by dnagoda** [comment]
Hi @hashcott 👋 

For Customer Accounts targets, we don't currently provide a hook for `checkoutToken`. You can use the value like this:

```
const checkoutToken = useSubscription(useApi().checkoutToken);
```
