### ISSUE TITLE
Docs Gen: Move Checkout extensions API reference to `/api/` rather than `/beta/`

### ISSUE THREAD

**Issue by jamesvidler** [Shopify/ui-extensions#293]
Drop API references in /api rather than /beta
Drop component references in /api rather than /beta

The doc gen script should output those files in the `/api` directory within `shopify-dev`.

**Comment by rennyG** [comment]
> @rennyG since we are already using this link (https://shopify-dev-staging2.shopifycloud.com/api/checkout-extensions/extension-points/api) for post-purchase, what link would the checkout extensions extension-points api use?
> Ren: Yeah we're running into challenges here because post-purchase paths were names a little generically. The IA/directory structure in `shopify-dev` is what's used to construct the URL. Looking at the IA under `/api`, we're using`/api/checkout-extensions/checkout/extension-points/api`.
> Also, if we are getting rid of the `/beta` will this mean these docs will not be public anymore unless the feature flag is enabled?
Yep exactly. Come Editions, I expect my process will be to enable the `checkout_extensions` feature flag for Shopify.dev, at which point all content will be public. I'll clean up the code to remove the feature flags from the pages and the script and such after the june edition.
