### ISSUE TITLE
Add a Date picker form field component

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#390]
## Please list the related package(s)

checkout-ui-extensions-react

## If this related to specific APIs or components, please list them here

Textfield 

## Describe the changes you are looking for

Can we consider adding a date picker as a ui component? Even just using TextField + browser date field.https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

The use case is delivery date form field for products that require specifying a date such as flower delivery or food where the customer has to be home to receive.

## Describe alternatives you’ve considered

Textfield with custom formatting to enter a date (prone to error from customers) and a custom Polaris-like calendar component using buttons.

**Comment by gil--** [comment]
No longer need this since I implemented my own custom picker

**Comment by gil--** [comment]
Ah sorry reopened.

**Comment by gil--** [comment]
@reigelgallarde-me Implemented a custom date picker using the available components + Javascript dates

![image](https://user-images.githubusercontent.com/3484527/207394890-f2b93798-f26c-4a4a-8ea4-b8626c6d132f.png)

**Comment by RishabhTayal** [comment]
Interesting. Any chance this code can be reused?

**Comment by reigelgallarde-me** [comment]
@gil-- can you share how you add the script? Is it external link?

**Comment by cdarland** [comment]
> Hey @RishabhTayal. Our projection is that `DatePicker` will ship publicly in our first package update of 2023. The specific date is still TBD, but keep an eye out in late January/early February.

Quick update for everyone awaiting this component. You can expect the `DatePicker` to ship in our March package release.

Thanks for hanging in there, and apologies for the recalibration.

**Comment by akatigbak** [comment]
good morning/afternoon/evening folks! Datepicker as an out of the box component has officially been released in the checkout extensibility package. 

Thank you for your patience. Closing this one now. Let us know how it goes!
