### ISSUE TITLE
Shipping options change React hook

### ISSUE THREAD

**Issue by mirceapiturca** [Shopify/ui-extensions#406]
## Please list the related package(s)
 checkout-ui-extensions

## If this related to specific APIs or components, please list them here
Related to: https://shopify.dev/api/checkout-extensions/checkout/extension-points/api#react-hooks

## Is your feature request related to a problem? Please describe.
Implementing functionality based on the selected shipping options is not possible. The current React hooks do not provide a way of knowing what shipping option is selected on checkout.

## Describe the changes you are looking for
A react hook, e.g.: `useShipping`, would return the current shipping option selected by the user for the checkout, and automatically re-render the component if the shipping option is changed.

## Describe alternatives you’ve considered
A Javascript event listener can be added on in `checkout.liquid`. But this is an unmaintainable solution that could be resolved in a "native" way.

## Additional context
Discussed on Slack here: https://app.slack.com/client/T4BB7S7HP/C0289HN2XHS/thread/C0289HN2XHS-1657693545.284219?cdn_fallback=2

**Comment by gil--** [comment]
Jobs to be done:
- Show custom fields based on the shipping option selected. For example: delivery notes when selecting white glove shipping or for more expensive shipping types, allow custom fields to specify insurance or delivery windows. Would only be possible through surfacing the selected shipping method.

**Comment by mirceapiturca** [comment]
@stansm No.
You can use this only if you have access to `checkout.liquid`, Plus accounts, and add your own custom JavaScript to the template. This is one thing UI extensions want to avoid.

**Comment by DevStar0202** [comment]
thanks. mirceapiturca.

**Comment by jarthorn** [comment]
I saw another request for this feature on the Shopify Partners slack today. Just adding the +1 here to help with our prioritization.

**Comment by GYMarshy** [comment]
We currently have to customise the checkout.liquid and add write a lot of JS to offer the following types of shipping methods:

- Named day (via a datepicker)
- Collection point (via a map / list of points)

Both of these types of shipping methods have become fairly commonplace, and are essential if our merchants are to offer shipping options that rival Amazon, or brands on other ecomm platforms etc.

It's not enough to just offer a datepicker or map UI element though. The list of available dates or locations can vary depending on the cart contents. What we would love is to see some kind of tie-up between these front end elements and the Carrier Service functionality. The flow would work as follows:

- Customer enters address (as now)
- Carrier service is called (as now)
- Carrier service returns list of methods (as now)
- Some of these methods may return a list of dates or locations (as well as title & price)
- User selects a method, and the appropriate UI appears to gather the extra data 
- Extra data is attached to the order as a metafield

We currently have carrier services working in exactly this way - calling 3rd party shipping providers to generate the list of options or a merchant's own systems to get a list of stores from which the order could be 'click & collected'. If we could deploy the UI in a more native way, our merchants would be able to offer a competitive range of shipping methods.

**Comment by mirceapiturca** [comment]
@jarthorn the initial request is related to @GYMarshy use case. Subscribing to shipping option changes should allow you to update or define a custom UI using the checkout UI components.

**Comment by jarthorn** [comment]
With the shipping options react hook alone, an extension could render additional fields above or below the shipping methods list. It sounded like Chris was looking to build a custom UI within a particular shipping method in the list. A screenshot of the experience you are looking for might help to clear up the confusion here.

**Comment by mirceapiturca** [comment]
Thank you for the clarification @jarthorn. I misunderstood. You are correct.

**Comment by GYMarshy** [comment]
Thanks @jarthorn - I'll open a new issue, copy the above comment and add an example from a current store.

**Comment by GYMarshy** [comment]
Is this on the roadmap @jarthorn ? Is there any update on when it might appear if so?

**Comment by RomainDW** [comment]
+1

**Comment by ralfatgadget** [comment]
+1

**Comment by gerwinbrunner** [comment]
+1

**Comment by colinbrogan** [comment]
+1

**Comment by Abner-J-Hdz** [comment]
I think "useShipping" should return more data such as if the order is pickup or ship, I even think it should be a separate hook as many stores use this native shopify option. 
Inside shopify/checkout-ui-extensions-react it should include events to which we could subscribe and these in listening mode, I think there are still many things missing to give a good customization to the checkout.

**Comment by Rronz** [comment]
+1

**Comment by colinbrogan** [comment]
This looks to be exactly what I had in mind, though I would need to test it to confirm.
I noticed in the API dropdown on those pages it says "unstable". I'm guessing these are all brand new features, and we would need to install some sort of nightly build to test them?

**Comment by TheSecurityDev** [comment]
> This looks to be exactly what I had in mind, though I would need to test it to confirm. I noticed in the API dropdown on those pages it says "unstable". I'm guessing these are all brand new features, and we would need to install some sort of nightly build to test them?

No, all the extension APIs are unstable while in beta, and can be used by installing the latest version of the checkout extensions package, as far as I know.

**Comment by jarthorn** [comment]
Belated update on this issue, but this feature has been shipped. See [useDeliveryGroups](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/delivery/usedeliverygroups) for the React hook, and [deliveryGroups](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/standardapi#properties-propertydetail-deliverygroups) in the imperative API. These provide both the list of available shipping options, as well as the currently selected option.
