### ISSUE TITLE
It looks like useBuyerJourney is not working.

### ISSUE THREAD

**Issue by ryujimorimoto** [Shopify/ui-extensions#427]
## Package and version
checkout-ui-extensions-react V0.17.1

## Describe the bug
I tried to work of a useBuyerJourney, but it looks like is not working.
I specified the argument to {behavior: allow}, but the customer is no longer able to continue with the purchase.
I wrote the code as follows:
```javascript
const buyerJourney = useBuyerJourney(); // ユーザーの購入過程を取得するためのhook
  buyerJourney.intercept({
    behavior: "allow"
  })
```
## Steps to reproduce the behavior:

1.  Run "yarn scaffold extension", or "shopify app scaffold extension",  and select a "checkout-ui".
2.  Inside a function App write the following code
```
const buyerJourney = useBuyerJourney(); // ユーザーの購入過程を取得するためのhook
  buyerJourney.intercept({
    behavior: "allow"
  })
```
3. Run "yarn dev", and open the preview checkout-ui.
4. Customers can confirm that they will no longer be able to purchase.

## Short video
https://user-images.githubusercontent.com/24236526/183323761-53b29462-3482-406b-ade7-489beb83f0bf.mov

**Comment by marvinhagemeister** [comment]
@ryujimorimoto the `.intercept()` method [expects a callback](https://shopify.dev/api/checkout-extensions/checkout/extension-points/api#interceptor) instead of an object as the first argument .

```diff
  const buyerJourney = useBuyerJourney();
- buyerJourney.intercept({ behavior: "allow" });
+ buyerJourney.intercept(() => {
+   // Some logic here that decides if we should return block or allow
+   return { behavior: "allow" };
+ });
```
