### ISSUE TITLE
Hot Module Replacement (HMR) no longer working for checkout_ui_extension .js[x] files

### ISSUE THREAD

**Issue by pixelchutes** [Shopify/ui-extensions#449]
## Please list the package(s) involved in the issue, and include the version you are using

`@shopify/checkout-ui-extensions-react`: `v0.18.1`

## Describe the bug

Hot Module Replacement (HMR) in the developer tooling when working with `checkout_ui_extension` appears to have stopped working. Changes to `.jsx` files no longer seem to be monitored, and testing code changes now require a full reload.

## Steps to reproduce the behavior:

1. Open a Checkout UI extension project
1. Run `dev` to test the local development code via `ngrok` _(e.g. dev store w/ checkout extensibility developer preview)_
1. Confirm component is visible / rendered on the page
1. Make an edit to the `.jsx` (or `.js`) component source code
1. Notice how `dev` tail log for `extensions` debug does not catch / monitor the change, changes are not reflected in the browser
1. Manually reload the browser and you will start seeing the changes _(not via HMR)_

## Expected behavior

Making a change to `.jsx` (or `.js`) Checkout UI extension files in the project should be monitored / caught, and trigger HMR. _e.g. re-render modified components without a full page reload_

**Expected log:**
> extensions | extension-name (Build succeeded)

**Expected dev UX:**
HMR triggers, replacing impacted component(s). No full reload required.

## Additional context

Perhaps related to new `locales` watcher? Making a change to `[locale].json` is **correctly caught and extension is re-rendered!** However, changes to `.jsx` files used to have the same behavior but no longer trigger HMR.

> extensions | Watcher added for: extensions/extension-name/locales

**Comment by kumar303** [comment]
Hi @vividviolet -- This is the same issue as the CLI one, right? https://github.com/Shopify/cli/issues/345

**Comment by vividviolet** [comment]
@kumar303 Yes, it looks to be the same bug
