### ISSUE TITLE
Settings defined in shopify.ui.extension.toml file not working

### ISSUE THREAD

**Issue by jzier3** [Shopify/ui-extensions#458]
## Please list the package(s) involved in the issue, and include the version you are using
Using "@shopify/checkout-ui-extensions-react": "^0.18.1" 

Shopify cli ^3

## Describe the bug

Settings defined in the config file are not available in the checkout editor. Example from our config file, copied from the sample documentation: 
```
[settings]
  [[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner."
```

## Steps to reproduce the behavior:

1. Go to checkout editor
2. Add extension
3. Look for settings on right side

## Expected behavior

Expected to see settings

## Screenshots
![Screen Shot 2022-08-28 at 4 09 04 PM](https://user-images.githubusercontent.com/71882929/187075663-c0801264-38ff-4cf8-a5e5-a42ef5a3e0b1.png)

## Additional context
Link to checkout extension: 

https://partners.shopify.com/941756/apps/7334592513/extensions/checkout_ui_extension/14895120385

**Comment by jzier3** [comment]
@kumar303

**Comment by jun-shop** [comment]
👋 Hi there - I'm taking a look at this and it seems like you've uninstalled the app the ticket refers to - are you still experiencing the same problem with the new app?
