### ISSUE TITLE
Border prop does not work for `BlockStack` component from checkout-ui

### ISSUE THREAD

**Issue by meecrobe** [Shopify/ui-extensions#485]
## Please list the package(s) involved in the issue, and include the version you are using

`"@shopify/checkout-ui-extensions-react": "^0.18.1"`

## Describe the bug

The following code doesn't render a border around the `BlockStack` component:
```tsx
<BlockStack spacing="loose" border="base" borderWidth="base">
  {children}
</BlockStack>
```

## Steps to reproduce the behavior:

Render a `BlockStack` with `border` property.

## Expected behavior

A border should be rendered around the `BlockStack` component.

**Comment by jffortier** [comment]
Thanks for flagging the issue. We'll have a fix soon.
