### ISSUE TITLE
Wrong quantity when adding back a product immediately after it was removed

### ISSUE THREAD

**Issue by catalin-invisible** [Shopify/ui-extensions#488]
## Steps to reproduce the behavior:

1. removing a product with `applyCartLinesChange` -> `removeCartLine`
2. add it back again with `applyCartLinesChange` -> `addCartLine` (with `quantity: 1`)
3. The product now has a quantity of 2. It should have just 1.

## Screen capture

https://youtu.be/wngy0B02ieI

**Comment by sjanczy2** [comment]
May be fixed by https://github.com/Shopify/ui-extensions/issues/448, will test this one together to confirm.

**Comment by catalin-invisible** [comment]
Yes, I can no longer reproduce, thanks!
