### ISSUE TITLE
ReferenceId and Token missing?

### ISSUE THREAD

**Issue by ghost** [Shopify/ui-extensions#513]
## Please list the related package(s)

checkout-ui-extensions-react

## If this related to specific APIs or components, please list them here

Related to: https://shopify.dev/api/checkout-extensions/checkout/extension-points/api#react-hooks

## Is your feature request related to a problem? Please describe.

Security and identification

## Describe the changes you are looking for

As can be seen in the post-purchase-ui-extension documentation [here](https://shopify.dev/api/checkout-extensions/extension-points/api), it gives us:

1. A referenceId described as the "Initial purchase's unique identifier."
2. A token described as "JWT representing the input_data payload."

As far as I can tell both of these do not currently exist in the checkout-ui-exension implementation.
This makes it hard to identify anonymous users (1) and make sure network requests are coming from shopify (2).

Am I missing something?

## Describe alternatives you’ve considered

I'm thinking about hashing the cart-content with a date and time, but that doesn't feel like a solid solution.
No idea how to solve the missing token issue.

## Additional context

None

**Comment by brooklynite77** [comment]
Thanks @sjanczy2 

Any idea on a timeline? In my opinion it's currently virtually impossible to securely fetch any api without a token that is signed using the Shopify secret key server side. And that's something Shopify needs to provide since the extension is running on your servers. 

Until that is solved, this makes having network access pretty much useless.

**Comment by niinpatel** [comment]
Any update on this?

**Comment by jarthorn** [comment]
I believe this is now supported through the [sessionToken API](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/standardapi#properties-propertydetail-sessiontoken). You can use this API to sign any payload that is sent back to your app server, and verify that it came from Shopify. See also [session token examples](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/standardapi#example-session-token).
