### ISSUE TITLE
Feature request: Component that can display a map

### ISSUE THREAD

**Issue by jarthorn** [Shopify/ui-extensions#515]
## Please list the related package(s)

checkout-ui-extensions

## Is your feature request related to a problem? Please describe.

Several merchants and app developers have raised the need to display a map component within a checkout extension. For example, this could be used to display pick up locations.

## Describe the changes you are looking for

Either a specific Map component, or a component that can embed a map.

**Comment by darryn** [comment]
Adding another use case here.

* [Quick screencast of current implementation](https://screenshot.click/14-55-kt9gj-zhpo2.mp4)
* [Relevant store](https://www.lovisa.com.au/)

**Comment by jarthorn** [comment]
This has now [shipped](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/components/interactive/map). 🎉
