### ISSUE TITLE
Button height shorter with `<Icon>` than with text

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#527]
## Please list the package(s) involved in the issue, and include the version you are using

checkout-ui-extensions-react: 0.19.0

## Describe the bug

When using just an icon within the `<Button>`, it displays with a shorter height than using text:

![CleanShot 2022-09-30 at 17 21 13](https://user-images.githubusercontent.com/3484527/193427914-afcf6ed7-dd63-4039-90cd-d8a5235415ed.png)

## Steps to reproduce the behavior:

```js
<Button 
  kind="secondary" 
  accessibilityLabel="Add"
>
  <Icon source="checkmark" appearance="success" size="fill" />
</Button>
```

## Expected behavior

The button should have a consistent min-height regardless of text or icon

## Screenshots

See above.

**Comment by jun-shop** [comment]
I believe this should be resolved. I wasn't able to repro it, but here's what I ended up doing

```
      <InlineLayout spacing="base" padding="base" columns={['9fr', '1fr']} maxBlockSize={100}>
        <Stepper label="add a thing"></Stepper>
        <Button kind="secondary" accessibilityLabel="Add">
          <Icon source="checkmark" appearance="success" size="fill" />
        </Button>
      </InlineLayout>
```

I'm closing this out, but feel free to re-open if you feel it hasn't been adequately resolved
