### ISSUE TITLE
New protected customer requirements blocking access to dev stores and app using 2022-07 API version

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#528]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/checkout-ui-extensions-react v0.18.1
@shopify/checkout-ui-extensions-react v0.20.0

## Describe the bug

When accessing a checkout UI extension in prod or within a dev store my app cannot render. The console showed an error reading "TypeError: Cannot read properties of undefined (reading 'customer'). I haven't changed any code for the past couple days and it was working fine before, but today this error appeared.

It seemed to be due to the new protected customer data requirements, so I upgraded my extension package from 0.18.1 to 0.20.0 and a similar error occurred:

"Uncaught ScopeNotGrantedError: Using buyer identity requires having personal customer data permissions granted to your app."

My app was installed with access to read_customer and read_shipping, and is using API version 2022-07, but the extension seems to be enforcing requirements meant for API version 2022-10:

https://shopify.dev/apps/store/data-protection/protected-customer-data

I've since requested access to the protected customer scopes in my partner dashboard but the error still persists, regardless of whether I use 2022-07 or 2022-10 API versions. It's concerning because migrating from 2022-07 to 2022-10 requires app updates and approval of the protected data request, and GA is 2 days from now so I can't provide merchants access to these features despite the docs saying otherwise. 

## Steps to reproduce the behavior:

1. Create dev store with checkout extensibility enabled
2. Create checkout ui extension that makes use of useCustomer() or useShippingAddress() extension hooks
3. Render the extension using `npm run dev`

## Expected behavior

The app should render as usual, having access to both useCustomer and useShippingAddress extension hooks and their resulting resources. 

## Screenshots

<img width="585" alt="read_customer access error (shop has read_customer enabled) " src="https://user-images.githubusercontent.com/17548405/193430254-e3802d43-cbce-4149-b0a6-7b00aaad8bc4.png">
<img width="588" alt="Screen Shot 2022-10-01 at 5 03 36 PM" src="https://user-images.githubusercontent.com/17548405/193430258-c6078b82-b053-41c2-a694-917007bc5f07.png">

**Comment by brooklynite77** [comment]
Confirmed. I'm getting the same thing.

Btw, sounds like this is enforced for checkout extension access: "To protect merchants and their customers, apps that are distributed on the App Store and use Admin API version 2022-10 or later **or checkout UI extensions,** need to request access to customer data, like names, emails, and order history."

Let's hope Shopify grant us access in time :)

**Comment by gil--** [comment]
Not sure what you extension does but if you comment out useCustomer and useAddress, it should render fine. I did this to unblock developed at least. I'm sure it'll be resolved Monday.

**Comment by KTruong008** [comment]
Is there any way to update the scopes? I requested and got approved but I realized I missed a crucial one but now all the fields are greyed out.
