### ISSUE TITLE
Allow for default extension point placement

### ISSUE THREAD

**Issue by kylebuildsstuff** [Shopify/ui-extensions#562]
## Please list the related package(s)

checkout-ui-extensions, admin-ui-extensions-react

## Is your feature request related to a problem? Please describe.

There are over 5 extension points and it's cumbersome for merchants new to the checkout editor to try evaluate each slot for what is the optimal placement for a checkout UI extension. I think this leads to a poorer onboarding experience and higher uninstall rates.

I think we can provide a much smoother onboarding experience with default extension points so the merchant doesn't have to fiddle with positions every time but, by default, still get the optimal placement of the app.

**Comment by jamesvidler** [comment]
Hi @KTruong008, default placements for dynamic extensions is something we are looking into. That being said, have you considered using a [static extension point](https://shopify.dev/api/checkout-extensions/checkout#extension-points)? This enables you (the developer) to define the specific extension point(s) that should be allowed, giving you much more control.

**Comment by jamesvidler** [comment]
> can the merchant switch the extension placement from static to dynamic?
Yes! You can support multiple extension points including your preferred static extension point, as well as the `Checkout::Dynamic::Render` extension point. If you place the static extension point first in the list of supported `extension_points` in the `toml` then the extension will be placed there by default when you activate the extension.
