### ISSUE TITLE
Liquid customizations to most of checkout disabled when using checkout UI extension app

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#563]
## Describe the bug

When a merchant uses a checkout UI extension app, any changes to the `checkout.liquid` file are limited only to the order status page. 

The merchant is requesting for automatic expansion of the order summary details (on mobile), and usually this would be possible with a small script within `checkout.liquid`, but simultaneously using a checkout UI extension app seems to break this behaviour.

I'm not sure if this should be a bug or a feature request, but either way it's not something that was expected. Is there a workaround for this issue by any chance?

## Steps to reproduce the behavior:

1. Create checkout UI extension app
2. Active app in checkout editor within a Plus store
3. Navigate, within the theme files, to `checkout.liquid`

## Expected behavior

Changes to `checkout.liquid` would apply to checkout pages as usual

## Screenshots

<img width="1310" alt="Screen Shot 2022-10-16 at 6 20 37 PM" src="https://user-images.githubusercontent.com/17548405/196061965-e60a9ef1-53d8-400b-a465-4e712fc94753.png">

**Comment by gil--** [comment]
When a merchant utilizes checkout extensions, it replaces checkout.liquid as the checkout that renders extensions is incompatible with checkout.liquid.

I do think your point is worth discussing in that some merchants need control over the dom to handle common requests:
- Open cart on mobile by default
- Hide discount code form

These were both possible prior to extensions but no longer possible.
