### ISSUE TITLE
 [Checkout UI] `behavior: "block"` of `useBuyerJourneyIntercept` doesn't intercept checkout process

### ISSUE THREAD

**Issue by ShirasuGyoza** [Shopify/ui-extensions#602]
## Please list the package(s) involved in the issue, and include the version you are using
"@shopify/checkout-ui-extensions-react": "^0.20.0"

related components and apis:
`useIntercept()`
`useBuyerJourneyIntercept()`
`useExtensionCapability("block_progress")`

## Describe the bug
We are building app that validates input form of checkout and it intercepts progress of checkout if a value is invalid using `Allow app to block checkout` setting.
I found that the interceptor doesn't work and customers can proceed their checkout.

## Steps to reproduce the behavior:
1. create interceptor
    ```
    const blockSetting = useExtensionCapability("block_progress");
    
    useBuyerJourneyIntercept(() => {
      if (blockSetting && valueIsInvalid) {
        return {
          behavior: "block",
          reason: "some values are invalid",
          perform: result => {...}
        }
      }
    });
    ```
1. on App's setting of Checkout Editor, enable `Allow app to block checkout`
    <img width="294" alt="Screen Shot 2022-11-12 at 17 16 46" src="https://user-images.githubusercontent.com/31214487/201466080-2f7f2f4a-2f10-42a3-9665-835a6ae00757.png">

1. put invalid value to block process
2. press `continue to shipping` button to continue, and it navigates shipping page although the inputted value is invalid

## Expected behavior
Cannot proceed to shipping page if the inputted value is invalid and `Allow app to block checkout` enabled.

## Additional context
I think the interceptor was working properly until last week. 
I opened this issue #594 and closed this week (just in case).

**Comment by darryn** [comment]
I have come across a similar-yet-slightly-different issue. I'll add it to this thread for now, but let me know if it warrants a separate GH Issue.

The issue I came across was the `useBuyerJourneyIntercept` not working if the buyer had already proceeded to the next step before returning to the previous step and supplying invalid data...

https://screenshot.click/11-09-94lkg-rctvl.mp4

### Replication steps

1. As above
2. As above
3. Proceed to the step after that which holds the `useBuyerJourneyIntercept` function by supplying `valid` information
4. Return to the previous step of checkout which holds the `useBuyerJourneyIntercept` function
5. Supply invalid information to the `useBuyerJourneyIntercept` function
6. You will not be blocked.

**Comment by faouzioudouh** [comment]
This issue is related to some changes we introduced to buyer-journey API https://github.com/Shopify/checkout-web/pull/15766, to only run the buyer journey interceptor when the extension is rendered.

we used the flag `renderer.rendered` that indicates whether any UI is currently rendering the extension’s content to the screen. but seems like this `renderer.rendered` is `false` even though the extension is rendered, so either we misused it, or we need to subscribe to `renderer.rendered` changes, something like:

```js
  const renderedSub = createRemoteSubscribable({
    get current() {
      return renderer.rendered;
    },
    subscribe: (subscriber) => {
      const removeRenderSubscription = renderer.on('render', () => {
        subscriber(renderer.rendered);
      });

      const removeRemoveSubscription = renderer.on('remove', () => {
        subscriber(renderer.rendered);
      });

      const removeRestartSubscription = renderer.on('restart', () => {
        teardown();
      });

      const removeDestroySubscription = renderer.on('destroy', () => {
        teardown();
      });

      const teardown = () => {
        removeRenderSubscription();
        removeRemoveSubscription();
        removeRestartSubscription();
        removeDestroySubscription();
      };

      return teardown;
    },
  });
```

**Comment by faouzioudouh** [comment]
Hi @ShirasuGyoza & @darryn we just shipped a fix for both these issues.
Feel free to reopen if you are still having this issue with `useBuyerJourneyIntercept` API.

Thank you for reporting!

**Comment by naoyanickf** [comment]
@faouzioudouh hi, I have a question about useBuyerJourneyIntercept.

I'm writing a validation of shipping address.

as a premise, i put an input form for zip code on a cart page. this saves a value with cart attributes
I validate whether shipping address zip code and cart attributes zip code are same.

when using useBuyerJourneyIntercept, this works for a new shipping address. but this doesn't work already inputted and selected shipping address. it seems that useBuyerJourneyIntercept is not fired. 

how can I always fire useBuyerJourneyIntercept?

**Comment by muneebtanveer94** [comment]
@faouzioudouh I want this BuyerJourneyIntercept hook to be triggered on await call. Actually i want to validate data from third party and then apply this hook is this possible?
@all
