### ISSUE TITLE
Need Help Related Checkout-Ui-Extension With Select List

### ISSUE THREAD

**Issue by pramodw31** [Shopify/ui-extensions#603]
Hello,
I have created the select list successfully using the checkout extension.
But when I change the option it is not changing on the front.  please check:- https://d.pr/v/cUTzWM
It is happing because I use the applyCartLinesChange method inside the on-change method.

 
`onChange: (value) => {
const attributes = [
{
key: DELIVERY_ATTRIBUTE,
value: value
}
];

applyCartLinesChange({
type: 'updateCartLine',
id: target.current.lines[0].id,
attributes: attributes
}).then()
},`

Can anyone tell me what I am doing wrong.

**Comment by balaclark** [comment]
Hi! I wanted to check if you are still having this issue? From discussions with support this was related to metafield configuration in the admin?

Hopefully it is resolved now, otherwise let us know and we can take a further look.

**Comment by pramodw31** [comment]
as discussed sending here full file code:-

`import {extend, Select, Grid, View, GridItem, Text, Heading, Divider, BlockSpacer} from "@shopify/checkout-ui-extensions";

extend("Checkout::CartLineDetails::RenderAfter", (root, {target, applyCartLinesChange, appMetafields}) => {
    
   
    const select = root.createComponent(Select, {
      label: 'Country',
      value: '1',
      onChange: (value) => {
        console.log(value);
        const attributes = [
            {
            key: 'Store',
            value: 'pramod test'
            }
        ];
        applyCartLinesChange({
            type: 'updateCartLine',
            id: target.current.lines[0].id,
            attributes: attributes
        }).then(console.log)
    },

      options: [
        {
          value: '1',
          label: 'Pickup',
        },
        {
          value: '2',
          label: 'Ship',
        },        
      ],

    });
  
    root.appendChild(select);
  });
`

**Comment by pramodw31** [comment]
Yeah, it seems like fixed now. Thanks @Steve-D-Powell

**Comment by lemonmade** [comment]
To be safe, you probably want to update the props of the select component in its `onChange` callback:

```diff
import {extend, Select, Grid, View, GridItem, Text, Heading, Divider, BlockSpacer} from "@shopify/checkout-ui-extensions";

extend("Checkout::CartLineDetails::RenderAfter", (root, {target, applyCartLinesChange, appMetafields}) => {
    
   
    const select = root.createComponent(Select, {
      label: 'DeliveryType',
      value: '1',
      onChange: (value) => {
        console.log(value);
        const attributes = [
            {
            key: 'Store',
            value: 'pramod test'
            }
        ];
        applyCartLinesChange({
            type: 'updateCartLine',
            id: target.current.lines[0].id,
            attributes: attributes
        }).then(console.log)
    },

      options: [
        {
          value: '1',
          label: 'Pickup',
        },
        {
          value: '2',
          label: 'Ship',
        },        
      ],

    });
  
    root.appendChild(select);
  });
```

**Comment by pramodw31** [comment]
> ```diff
> select.updateProps({value});
> ```

Thanks @lemonmade 
I will try it.
