### ISSUE TITLE
Checkout UI Extensions - range slider input

### ISSUE THREAD

**Issue by wisniewski94** [Shopify/ui-extensions#622]
## Please list the related package(s)

checkout-ui-extensions
(and possibly any kind of ui extension as this is very generic request)

## Is your feature request related to a problem? Please describe.

Example: let the customer input points to exchange for a discount using a range slider.

## Describe the changes you are looking for

Attributes:
- min range value
- max range value
- step size
- event listener so we can print the currently selected value in other parts of the extension (e.g. after redeeming X points, Y will remain)

The most basic range slider using HTML:
`<input type="range">`

Polaris:
https://polaris.shopify.com/components/range-slider

Additional question:
Wouldn't it be easier to add all generic Polaris components to ui-extensions?

**Comment by owenanderson** [comment]
Hi @wisniewski94, thanks for the feedback! A while back, we did [explore adding a slider component](https://github.com/Shopify/ui-extensions/discussions/626), but opted not to as there's usability concerns with sliders and alternate patterns or components could be used to redeem points. Feel free to re-open if you have any new rationale, or comment on our slider component discussion.
