### ISSUE TITLE
[Checkout UI] Add `useApplyShippingAddress()`

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#630]
## Please list the related package(s)

checkout-ui-extensions-react

## If this related to specific APIs or components, please list them here

Shipping address

## Is your feature request related to a problem? Please describe.

Expose `useApplyShippingAddress` in order to allow extensions to modify the shipping address (address validation apps)

### Use cases
1. Correct malformed addresses such as when unit number is entered in address line 1 but shipping requires it to be present in line 2.
2. Allow customers to use a recommended address that includes corrections for typos such as a misspelt street name or city.

## Describe the changes you are looking for

I'd like a programatic method to update the shipping address for a customer. Potentially pass in key/value pairs to identify which address field should be updated?

### Example implementation on React JS

```jsx
 const applyShippingAddressChange = useApplyShippingAddressChange();

 applyShippingAddressChange({
   type: "updateAddress",
   key: "province",
   value: "New York",
 });
 ```
 
 The Storefront `checkoutShippingAddressUpdateV2` mutation is probably a good place for inspiration: https://shopify.dev/api/storefront/2022-10/mutations/checkoutShippingAddressUpdateV2 since it does this but via the SF API.

## Describe alternatives you’ve considered

N/A

## Additional context

Currently, many Shopify Plus merchants handle this via custom checkout.liquid logic

**Comment by TheSecurityDev** [comment]
Any updates on this?

**Comment by amoyano** [comment]
Any news on this? atm is there any way to fix this in Checkout UI? I'd need for example to force the format E164 in the address phone input

**Comment by gil--** [comment]
@amoyano One option is enforce using UI Extension buyer intercept to block checkout. https://shopify.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/buyer-journey/usebuyerjourneyintercept

**Comment by gil--** [comment]
@amoyano If you're doing a custom app (for a specific store not on app store) then it should not be required. If it's a public app, then you'd need to request access to shipping address.

**Comment by amoyano** [comment]
`import React from 'react';
import {
  render,
  useBuyerJourneyIntercept,
  useShippingAddress,
} from '@shopify/checkout-ui-extensions-react';
render(
  'Checkout::DeliveryAddress::RenderBefore',
  () => <Extension />,
);
function Extension() {
  const address = useShippingAddress();

  useBuyerJourneyIntercept(
    ({canBlockProgress}) => {
      return canBlockProgress &&
        address?.phone &&
        !address.phone.includes("+")
        ? {
            behavior: 'block',
            reason: 'Invalid Phone Number',
            errors: [
              {
                message:
                  'Please add country code to your phone number. Eg. +1 123 456 7890',
                // Show an error underneath the country code field
                target:
                  '$.cart.deliveryGroups[0].deliveryAddress.phone',
              },
              {
                // In addition, show an error at the page level
                message:
                  'Please check your phone number',
              },
            ],
          }
        : {
            behavior: 'allow',
          };
    },
  );

  return null;
}`

**Comment by amoyano** [comment]
import React from 'react';
import {
  render,
  useBuyerJourneyIntercept,
  useShippingAddress,
} from '@shopify/checkout-ui-extensions-react';
render(
  'Checkout::DeliveryAddress::RenderBefore',
  () => <Extension />,
);
function Extension() {
  const address = useShippingAddress();

  useBuyerJourneyIntercept(
    ({canBlockProgress}) => {
      return canBlockProgress &&
        address?.phone &&
        !address.phone.includes("+")
        ? {
            behavior: 'block',
            reason: 'Invalid Phone Number',
            errors: [
              {
                message:
                  'Please add country code to your phone number. Eg. +1 123 456 7890',
                // Show an error underneath the country code field
                target:
                  '$.cart.deliveryGroups[0].deliveryAddress.phone',
              },
              {
                // In addition, show an error at the page level
                message:
                  'Please check your phone number',
              },
            ],
          }
        : {
            behavior: 'allow',
          };
    },
  );

  return null;
}

**Comment by amoyano** [comment]
perfect to block the user... but atm we can't format in the backend and submit that one right? :/ Thanks becuase it helps too!

**Comment by jackdouglas** [comment]
> You'll have to wait for the native API to be release (i think roadmap shows by July?)

Please can you point me to the roadmap?

**Comment by amoyano** [comment]
@gil-- do you know if there is a way to get the Order ID, Order NUmber and ORder date? tried the UseExtension , {order} but is always undefined , also in the thank you page, after purchase... :/

**Comment by sjanczy2** [comment]
Closing as this was released at summer editions 👍

**Comment by bpfullmetal** [comment]
How do we upgrade to 2023-10? I've updated all packages to the latest versions but it's still showing 2023-04 in the useExtensionApi

**Comment by sjanczy2** [comment]
@jackdouglas If you don't mind, please open a new issue with steps to reproduce if you are having problems with the API

@bpfullmetal We don't yet have `2023-10` available, the latest stable release is `2023-10`.  In order to be on `2023-07` make sure you've followed the steps in this document https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/versioning-migration . If you have further issues feel free to open a new issue!
