### ISSUE TITLE
[Checkout UI] Overflow not hidden when `<View>` has border radius

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#631]
## Describe the bug

When a `<View>` component has a border radius with no padding and a child component such as an `Image` has no border radius, it bleeds into the border:

![CleanShot 2022-12-01 at 13 49 56](https://user-images.githubusercontent.com/3484527/205135895-270007a9-5c1b-442f-8507-c9f1382a4e62.png)

Is there any way to apply `overflow: hidden` to the `<View>` component so that the border radius is respected:

![CleanShot 2022-12-01 at 13 49 48](https://user-images.githubusercontent.com/3484527/205135979-80ae1c7b-4333-4730-a19b-8556a9c39690.png)

## Steps to reproduce the behavior:

```
<View border="base" borderRadius="base">
  <Image source="" />
</View>
```

## Expected behavior

I'd expect the border radius of the View component to be respected.

**Comment by balaclark** [comment]
Hi Gil, thanks for the report. 

Unfortunately we can’t set `overflow: hidden` on `View` as sometimes things have to leak through the border (e.g. round counter badge on a thumbnail, see screenshot).
For the Image inside View case we support borderRadius on Image.

<img width="94" alt="Screenshot 2022-12-02 at 11 15 13 AM" src="https://user-images.githubusercontent.com/285598/205344501-2bfc002c-2c77-48ef-aa10-e3f2372a2b5f.png">

```jsx
<View border="base" borderRadius="base">
  <Image source="" borderRadius="base" />
</View>
```

**Comment by gil--** [comment]
@balaclark !! I somehow did not realize the image could have borderRadius. That solved it and makes sense in context to the product quantity badge. Thank you!

Closing. Use solution in https://github.com/Shopify/ui-extensions/issues/631#issuecomment-1335531839
