### ISSUE TITLE
[Checkout UI] Spinner and Select Error

### ISSUE THREAD

**Issue by eni9889** [Shopify/ui-extensions#636]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/post-purchase-ui-react ^0.0.3

## Describe the bug

```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/packs/media/icons/spinner-ed9a4bc3.svg') is not a valid name.
```

## Steps to reproduce the behavior:

1. Import either the Spinner or the Select elements in a react project

## Expected behavior

It should show the element

**Comment by jffortier** [comment]
Hi @eni9889, can you provide a simplified version of your code that we can use to reproduce the issue on our side? Thanks.
