### ISSUE TITLE
Mark deprecated props in the docs

### ISSUE THREAD

**Issue by igor10k** [Shopify/ui-extensions#644]
Update the docgen script to mark props as deprecated when they are preceded by the `@deprecated` tsdoc decorator.

**Comment by cdarland** [comment]
@igor10k @oliverigor with the updated docs framework is this still a relevant issue?

**Comment by oliverigor** [comment]
Nope. 
Example here https://shopify-dev.ui-extension-gen-docs.igor-deoliveiramartins.us.spin.dev/api/checkout-ui-extensions/components/actions/button, check the `submit` prop. 

We can close this issue :D
