### ISSUE TITLE
maxInlineSize and minInlineSize with Integer value missing `px` in html

### ISSUE THREAD

**Issue by jduff** [Shopify/ui-extensions#662]
checkout-ui-extensions, latest

## Describe the bug

When using `maxInlineSize`, `minInlineSize`, `minBlockSize`, `maxBlockSize` etc the docs say you can use an integer value which is the size in pixels. When the html is rendered this number is missing the `px` unit so doesn't do anything.

```
<InlineLayout
  spacing='none'
  blockAlignment='center'
  columns=${['fill', 'auto']}
  maxInlineSize='400'
  minInlineSize='300'>
</InlineLayout>
```

<img width="319" alt="Screenshot 2022-12-14 at 8 39 32 PM" src="https://user-images.githubusercontent.com/441/207752358-70b16bc2-60ee-41c2-a093-6478cbaf6d4a.png">

If I add `px` to the end of the `400` and `300` in the css inspector then it does work correctly.

## Expected behavior

The css variable generated should be in pixels so the min and max width can be set.

## Additional Context

I am using the `htm` render from `remote-ui`, not the react renderer or components.

**Comment by ncardeli** [comment]
hey John!

Have you tried passing the `maxInlineSize` and `minInlineSize` props values as interpolated values? 
That way they should be passed to the component as numbers instead of strings, which is probably the cause of the issue.

```htm
<InlineLayout
  spacing='none'
  blockAlignment='center'
  columns=${['fill', 'auto']}
  maxInlineSize=${400}
  minInlineSize=${300}>
</InlineLayout>
```

**Comment by jduff** [comment]
❤️ thanks @ncardeli that did it for me! I tried everything except that 🤦
