### ISSUE TITLE
applyCartLinesChange missing sellingPlanId

### ISSUE THREAD

**Issue by sebinievas** [Shopify/ui-extensions#709]
## Please list the related package(s)

checkout-ui-extensions

## If this related to specific APIs or components, please list them here

`applyCartLinesChange`

## Is your feature request related to a problem? Please describe.

It seems that `sellingPlanId` is missing (possible oversight) from the API `applyCartLinesChange` as I cannot reference a specific selling plan or subscription we'd like to include as an upsell.

## Describe the changes you are looking for

Add the prop `sellingPlanId` to the `applyCartLinesChange` API for the various interfaces.

## Describe alternatives you’ve considered

Tried to get access to query from the `useExtensionsAPI` to attempt to mutate the cart directly but I got scared and went under my blanket.

## Additional context

N/A

**Comment by sebinievas** [comment]
No problem thanks!

**Comment by kumar303** [comment]
Just to be clear, [this issue](https://github.com/Shopify/ui-extensions/issues/408) was about reading `sellingPlanId`. The request here is about _writing_ `sellingPlanId` while calling `applyCartLinesChange()`, similar to the [cartLinesUpdate](https://shopify.dev/docs/api/storefront/2022-04/mutations/cartLinesUpdate) mutation.

**Comment by sebinievas** [comment]
Thanks for catching that! That would’ve been forgotten and back burned! Yes
please we need to be able to pass sellingPlanId !!!

**Comment by sebinievas** [comment]
@sjanczy2 Will you please re-open this so it is addressed?

**Comment by sebinievas** [comment]
@sjanczy2 Any idea if this is something that would be ready for April's API update? I don't think this is a big change.

**Comment by athails** [comment]
Hey @sjanczy2 would be great to have an update on the timeline here. We are stuck on some work as we cannot write the selling plan. Thanks in advance for your time

**Comment by sebinievas** [comment]
@sjanczy2 any news on this?

**Comment by cpeddecord** [comment]
@catalin-invisible awesome, thank you for that very detailed video and explanation, let me see if I can reproduce on my end.

**Comment by catalin-invisible** [comment]
@cpeddecord this still does not work
