### ISSUE TITLE
[Checkout UI] cart attributes do not persist 

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#744]
## Please list the package(s) involved in the issue, and include the version you are using

checkout-ui-extensions-react: 0.24.0

## Describe the bug

When applying a new cart attribute via `useApplyAttributeChange`, the attributes show up on the extension api. If we refresh checkout or proceed to a new step, the attributes vanish. I don't remember this happening so I think this is a regression.

I can't duplicate this behavior for `useApplyNoteChange` or `useApplyMetafieldsChange`. So it seems limited to attributes.

## Steps to reproduce the behavior:

1. Apply an attribute via:
```js
const applyAttributeChange = useApplyAttributeChange();

useEffect(() => {
applyAttributeChange({
                type: "updateAttribute",
                key: 'hello',
                value: `world`,
});
}, []);
```

2. Notice the attributes appear.
3. Reload the checkout page and read the `useExtensionApi.attributes.current` and they will be missing.

## Expected behavior

I would expect attributes applied via ui extensions within checkout to persist across page reloads and step changes.

**Comment by ndefie** [comment]
This is also true for me +1

**Comment by dnagoda** [comment]
Hi @gil--, @yuzushioh and @ndefie. We shipped a fix for this. If you're still having issues with custom attributes, please let us know.

**Comment by awd** [comment]
Hello - currently seeing this behaviour on API 2023-10, and @shopify/ui-extensions-react ^2023.10.0
