### ISSUE TITLE
[Checkou UI] `useAttribute` hooks

### ISSUE THREAD

**Issue by yuzushioh** [Shopify/ui-extensions#750]
## Please list the related package(s)

`checkout-ui-extensions-react: 0.24.0`

## If this related to specific APIs or components, please list them here

- `useAttributes`

## Is your feature request related to a problem? Please describe.

- Get a single attribute by specifying a attribute key

## Describe the changes you are looking for

- Provide a `useAttribute(filter: AttributeFilter) => Attribute | undefined` API

**Comment by jamesvidler** [comment]
Closing this issue since [useAttributeValues()](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/attributes#useAttributeValues) has been released.

```javascript
const [buyerSelectedFreeTShirt, tshirtSize] =
    useAttributeValues([
      'buyerSelectedFreeTShirt',
      'tshirtSize',
    ]);
```
