### ISSUE TITLE
[Branding Api] Expose backgroundColor on CheckoutBrandingMerchandiseThumbnail

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#782]
## Please list the related package(s)

Admin API

## If this related to specific APIs or components, please list them here

- [checkoutBranding](https://shopify.dev/docs/api/admin-graphql/unstable/objects/CheckoutBranding) object
- [CheckoutBrandingDesignSystemInput](https://shopify.dev/docs/api/admin-graphql/unstable/input-objects/CheckoutBrandingDesignSystemInput) object

## Is your feature request related to a problem? Please describe.

Trying to change media image background color which isn't possible currently. Current it's transparent but it would be nice if we could set it as transparent or white or reference a color group.

![CleanShot 2023-03-08 at 16 19 49](https://user-images.githubusercontent.com/3484527/223854681-f8c37f9e-2046-4b6f-9464-2eab2101abf8.png)

## Describe the changes you are looking for

Surface a new [CheckoutBrandingColorSelection](https://shopify.dev/docs/api/admin-graphql/unstable/enums/CheckoutBrandingColorSelection)  property on [CheckoutBrandingMerchandiseThumbnail](https://shopify.dev/docs/api/admin-graphql/unstable/objects/CheckoutBrandingMerchandiseThumbnail). Ideally named backgroundColor. Would be nice if white was added as an option to CheckoutBrandingColorSelection.

## Describe alternatives you’ve considered

I'm not sure if this is on the June roadmap but figured I'd put in a "request":

![CleanShot 2023-03-08 at 16 15 24](https://user-images.githubusercontent.com/3484527/223852138-cca2503a-d5a4-4117-b0e9-14be9e16827f.png)

**Comment by owenanderson** [comment]
Thanks for sharing @gil--.  It's on our roadmap to add some new color properties, so we'll keep this one in mind. Are you wanting to apply a specific property like white or transparent, or are you more trying say "match thumbnail" colors?

**Comment by jun-shop** [comment]
Going to close this out as won't do, but feel free to re-open if you feel strongly about this as an ask
