### ISSUE TITLE
Checkout Editor breaks when adding app

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#824]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/checkout-ui-extensions-react": "0.24.0",
"@shopify/cli": "^3.43.0",

## Describe the bug

Checkout editor loads a 500 error page when adding app.

## Steps to reproduce the behavior:

1. Open checkout editor
2. Add app

## Expected behavior

Checkout editor should load app into preview

## Screenshots

<img width="718" alt="Screen Shot 2023-03-28 at 2 14 07 PM" src="https://user-images.githubusercontent.com/17548405/228330748-d715dee2-0ede-40e4-82a0-f4e1bdaae3bd.png">
<img width="805" alt="Screen Shot 2023-03-29 at 11 42 37 AM" src="https://user-images.githubusercontent.com/17548405/228594008-283422a5-a1da-4da2-9abb-ba7d2d8ea8cd.png">

https://youtu.be/iU0S5Fe7i6I

## Additional context

It was working fine just an hour ago, and I haven't changed or pushed any code since last week. Status pages reports all systems are operational

**Comment by dani-sanomads** [comment]
I'm facing similar issue but when i click on the app block for editing it take to me to error 500.

**Comment by jamesvidler** [comment]
@KTruong008 / @dani-sanomads are you still experiencing this error?

**Comment by KTruong008** [comment]
> @KTruong008 / @dani-sanomads are you still experiencing this error?

Looks like it. Just tried it now with a hard refresh, here's what I'm seeing:

https://youtu.be/SxwOLH1E8Bc

**Comment by jamesvidler** [comment]
We have reproduced the issue relating to metafields, and our team is working on a fix.

**Comment by KTruong008** [comment]
> @KTruong008 The fix has been deployed to production. Could you please verify it? Please let us know if everything works again? Thank you!

@dong-qian It looks good, issue isn't appearing anymore, thank you for the fix! :pray:
