### ISSUE TITLE
[Checkout UI extension] useApplyCartLinesChange always return CartLineChangeResultError if previous query return error

### ISSUE THREAD

**Issue by DunggNguyenn** [Shopify/ui-extensions#827]
## Package

-  "@shopify/app": "3.41.2",

-    "@shopify/checkout-ui-extensions-react": "^0.24.0",
- "@shopify/cli": "3.41.2",
- "react": "^17.0.2"

## Describe the bug
I create a product offer list by checkout UI extension component and API.

This is the function to handle clicking "Add to cart" button:
```
const applyCartLinesChange = useApplyCartLinesChange()
const onClickAddToCart = async () => {
let result = await applyCartLinesChange({
        type: 'addCartLine',
        merchandiseId: currentVariant.variant.id,
        quantity: currentVariant.quantity
      })
}
```

At the start, if I add a product that is not out of stock => the result.type = 'success'.
Then I add a product that is OUT OF STOCK => all results after that will be {type: 'error', message: 'This item is out of stock.'} although the other products are NOT out of stock

## Loom: https://www.loom.com/share/985cf60523eb41ef9bcb2645421c87d8

Please check and fix this bug. Thank you!

**Comment by posth** [comment]
@Shopify/checkout-extensibility could you asses the severity please?

**Comment by jarthorn** [comment]
Very stale issue, please reopen if there is still a reproducible problem here.
