### ISSUE TITLE
Send custom data to checkout ui extension

### ISSUE THREAD

**Issue by Blqck666** [Shopify/ui-extensions#848]
I've started working with checkout ui extension recently and i want to know if is it possible to add custom data in product page (let's say it's a checkbox, or anything else) and check if that check box is selected in the checkout ui extension so i can show a text field when adding the shipping address

**Comment by jamesvidler** [comment]
The [checkout ui extensions API](https://shopify.dev/docs/api/checkout-ui-extensions/apis/standardapi) allows you to read custom line item attributes via the `lines` property. Each `CartLine` has an array of `attributes` which can be read.
![Screenshot 2023-04-06 at 4 06 36 PM](https://user-images.githubusercontent.com/12719665/230483402-a468c4b4-67f4-415d-a8a4-502714acf03b.png)
You can set line item properties on the product page by following [these instructions](https://community.shopify.com/c/shopify-design/product-pages-get-customization-information-for-products/td-p/616503).

**Comment by Blqck666** [comment]
Thanks james,

does these attribute can be hidden from the customer ?

**Comment by jamesvidler** [comment]
Yes, they can be set with a hidden input on the product page and if you use a name like `_myAttribute` then it will also be hidden on the checkout page.

**Comment by Blqck666** [comment]
Thx for your help 🙌
