### ISSUE TITLE
"Component" cannot be used as a JSX component

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#867]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/app": "^3.43.0",
"@shopify/checkout-ui-extensions-react": "0.24.0",
"@shopify/cli": "^3.43.0",
"@shopify/web-pixels-extension": "^0.1.5",
"react": "^17.0.2"
```

## Describe the bug

Any component I import and use from `@shopify/checkout-ui-extensions-react` creates a type issue within the VS code editor.

## Steps to reproduce the behavior:

1. Start UI extension app
2. Import & use UI component from `checkout-ui-extensions-react`

## Expected behavior

I expected to be able to use the components without type errors as I've used the syntax and added the necessary props as described by the docs.

## Screenshots
<img width="659" alt="Screen Shot 2023-04-13 at 6 23 40 PM" src="https://user-images.githubusercontent.com/17548405/231896437-f4055dcd-32db-46e5-b518-429c9f9fff87.png">

## Additional context

This issue has been with me for months now. I thought it'd go away after a while and I tried upgrading Shopify CLI too but it still persists. The only solution I've found was to sprinkle `// @ts-ignore` everywhere but that makes it so actual errors are hidden.

**Comment by simontaisne** [comment]
Hey @KTruong008, have you selected the `TypeScript React` language for your checkout UI extension?

**Comment by KTruong008** [comment]
> Hey @KTruong008, have you selected the TypeScript React language for your checkout UI extension?

I'm pretty sure I did but is there a way to verify or update if I didn't? I created this extension back in September 2022.

**Comment by simontaisne** [comment]
Do you have a similar `.tsconfig` in your extension folder?

```
{
  // This tsconfig.json file is only needed to inform the IDE
  // About the `react-jsx` tsconfig option, so IDE don't complain about missing react import
  // Changing options here won't affect the build of your extension
  "compilerOptions": {
    "jsx": "react-jsx",
    "esModuleInterop": true,
    "strict": true
  },
  "include": ["./src"]
}
```
