### ISSUE TITLE
Load on OrderStatus page

### ISSUE THREAD

**Issue by marcmayo** [Shopify/ui-extensions#885]
I went through the whole shopify documentation and the only thing I could find was this image here https://shopify.dev/docs/api/checkout-ui-extensions/extension-points-overview#supported-locations-order-status

But no documentation on how to load it on the orderstatuspage - also the getting started doesn't say anything about it - it says to use dynamic render... but the shopify admin himself can't add it to the Order status page.

Any suggestions?

**Comment by dmhenry** [comment]
`Checkout::Dynamic::Render` is a [dynamic](https://shopify.dev/docs/apps/checkout/best-practices/testing-ui-extensions#dynamic-extension-points) Checkout UI extension point and is currently available as a [developer preview](https://shopify.dev/docs/api/release-notes/developer-previews#checkout-extensibility-developer-preview). [Previewing](https://shopify.dev/docs/api/release-notes/developer-previews#previewing-new-features) requires [creation](https://shopify.dev/docs/api/release-notes/developer-previews#steps) of a Development store with the "Checkout Extensibility" Developer Preview enabled. This [tutorial](https://shopify.dev/docs/apps/checkout/product-offers/pre-purchase/getting-started) uses the `Checkout::Dynamic::Render` extension point with the `ORDER_SUMMARY4` and is very like what you're trying to achieve.

**Comment by marcmayo** [comment]
﻿No, what I’d like to achieve is this:
https://shopify.dev/docs/apps/checkout/order-status-page/getting-started
but even the tutorial doesn’t render it at the order status page

Marc Mayr
Clauma Marketing GmbH
Max-Stromeyer-Str. 116
78467 Germany

Phone: +49 7531 1279530
E-Mail: ***@***.******@***.***>
Website: clauma-marketing.com<https://www.clauma-marketing.com/>

Von: Dave Henry ***@***.***>
Datum: Freitag, 21. April 2023 um 17:54
An: Shopify/ui-extensions ***@***.***>
Cc: Marc Mayr ***@***.***>, Author ***@***.***>
Betreff: Re: [Shopify/ui-extensions] Load on OrderStatus page (Issue #885)

Checkout::Dynamic::Render is a dynamic<https://shopify.dev/docs/apps/checkout/best-practices/testing-ui-extensions#dynamic-extension-points> Checkout UI extension point and is currently available as a developer preview<https://shopify.dev/docs/api/release-notes/developer-previews#checkout-extensibility-developer-preview>. Previewing<https://shopify.dev/docs/api/release-notes/developer-previews#previewing-new-features> requires creation<https://shopify.dev/docs/api/release-notes/developer-previews#steps> of a Development store with the "Checkout Extensibility" Developer Preview enabled. This tutorial<https://shopify.dev/docs/apps/checkout/product-offers/pre-purchase/getting-started> uses the Checkout::Dynamic::Render extension point with the ORDER_SUMMARY4 and is very like what you're trying to achieve.

**Comment by lucasprag** [comment]
I'm also trying the same thing. I'm able to place (using the Shopify Checkout Editor) & render checkout extensions anywhere, but the order status page. I'm guessing this is still under development at Shopify.

**Comment by dmhenry** [comment]
I apologize for the confusion -- this could stand to be a bit clearer. Using the tutorial, I do see the Order Status extension based on the tutorial:

<img width="1201" alt="Screenshot 2023-04-21 at 4 14 53 PM" src="https://user-images.githubusercontent.com/4490738/233726663-d28b5957-d539-477e-9322-a487ed7844d1.png">

Just to verify, your development store was set up with the [Developer Preview Checkout Extension](https://shopify.dev/docs/api/release-notes/developer-previews#steps) build?

<img width="593" alt="Screenshot 2023-04-21 at 4 13 44 PM" src="https://user-images.githubusercontent.com/4490738/233726483-a103dd63-f48e-4c00-8794-07aeaff9e982.png">

 You should see this in the Store Admin:

<img width="224" alt="Screenshot 2023-04-21 at 4 08 14 PM" src="https://user-images.githubusercontent.com/4490738/233725659-dd98fdce-1bea-429f-aa8a-c64a8004a7e5.png">

**Comment by lucasprag** [comment]
When I followed the tutorial, I used a store with developer preview checkout extensibility, but couldn't get the extension to show in the order status page 😞 

![Screen Shot 2023-05-01 at 1 50 39 PM](https://user-images.githubusercontent.com/2293178/235500598-089e190a-5c8f-4338-9a01-533d31a6991f.png)
![Screen Shot 2023-05-01 at 1 50 51 PM](https://user-images.githubusercontent.com/2293178/235500600-68416c74-863b-42bc-a186-1135ce4c3e82.png)

**Comment by jarthorn** [comment]
Extensions are now supported on the Order status page: https://shopify.dev/docs/apps/checkout/thank-you-order-status
