### ISSUE TITLE
[Checkout-UI] Load extensions only for specific viewports

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#886]
## Please list the related package(s)

checkout-ui-extensions

## Is your feature request related to a problem? Please describe.

Please consider surfacing an option within the checkout editor at the extension level to render the extension for specific breakpoints. There are use-cases where information is added to the sidebar that is then hidden on mobile. A common approach is to then show that information in the main content area so that it's visible but the merchant does not want that on desktop.

![CleanShot 2023-04-20 at 15 26 28@2x](https://user-images.githubusercontent.com/3484527/233469310-c38ca030-b951-4847-98ab-3bfdb76b3976.png)
![CleanShot 2023-04-20 at 15 26 36@2x](https://user-images.githubusercontent.com/3484527/233469317-7c1dfe63-b759-43ee-a25d-d8219827b148.png)

## Describe the changes you are looking for

Adding a new checkout editor setting (similar to "Show on shop pay") that determines if an extension is loaded on mobile-only, desktop-only, or always shown.

## Describe alternatives you’ve considered

Asking them to choose a different extension point that is visible across breakpoints.

**Comment by jamesvidler** [comment]
Hi @gil--, thank you for submitting this feedback! We will share this with the product team to review. For the specific use case you pointed out, it is worth noting this works a little differently right now in multi-page checkout vs one-page checkout.

**Multi-page checkout**:
Hidden by default, within the Order Summary rollup.
![Screenshot 2023-04-24 at 9 24 16 AM](https://user-images.githubusercontent.com/12719665/234010529-8baf616d-f923-45ef-b0c6-cf882965d436.png)

**One-page checkout**:
Appears visible in the order summary at the bottom of the page within the main column.
![Screenshot 2023-04-24 at 9 26 46 AM](https://user-images.githubusercontent.com/12719665/234010759-a5e48e0a-1058-4430-9aea-82f8df669de6.png)

**Comment by jarthorn** [comment]
>Please consider surfacing an option within the checkout editor at the extension level to render the extension for specific breakpoints.

@gil-- can you clarify if you meant to say **viewports** here rather than **breakpoints**? Our current thinking is that we would enable extension implementations to selectively hide components based on viewport size, rather than this being a merchant configuration choice. That way an extension implementation could provide desktop and mobile layouts and they would be applied automatically. It sounds like you are asking for a merchant configuration option but this puts the responsive design complexity onto them rather than the developer.

**Comment by kpeatt** [comment]
@ncardeli Is there a plan for the `Display` property to work for the above layout components when using `unstable` inside of New Customer Accounts? Currently, nothing happens when you try to use `display` properties on those components in those areas. See #2158

**Comment by ncardeli** [comment]
@kpeatt It will be available in Customer Accounts in the next few days 👍

**Comment by jarthorn** [comment]
I'm going to close this issue since this feature has been implemented, and is available in the latest stable release (`2024-07`)
