### ISSUE TITLE
Checkout UI: `Checkout::Dynamic::Render[Wallets1]` has spacing bug

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#914]
## Please list the package(s) involved in the issue, and include the version you are using

checkout core

## Describe the bug

Wallets1 dynamic render point has an extra div being added which is causing extra padding to show. Numerous Plus merchants have sent me a complaint asking how to remove the extra spacing between the extension and the wallets.

## Steps to reproduce the behavior:

1. Enable a wallet payment such as Shopify Payments + Google Pay
2. Add a barebones extensions with <Text>Hey</Text>
3. Enable on `?placement-reference=WALLETS1`
4. Notice extra spacing between extension and wallets 

## Expected behavior

I would expect normal spacing and not the extra div causing padding bloat.

## Screenshots

<img width="606" alt="CleanShot 2023-05-03 at 10 13 03@2x" src="https://user-images.githubusercontent.com/3484527/235942587-e8429f01-9a37-493c-a0ca-076ff5dc2120.png">
<img width="943" alt="CleanShot 2023-05-03 at 10 13 15@2x" src="https://user-images.githubusercontent.com/3484527/235942600-74fb223a-1d9f-421a-952d-c6348f6435ee.png">
<img width="634" alt="CleanShot 2023-05-03 at 09 55 57@2x" src="https://user-images.githubusercontent.com/3484527/235942940-b88298db-864c-42ad-962d-608effbd0de2.png">

## Additional context

n/a

**Comment by jarthorn** [comment]
This appears to be fixed, I no longer see this extra padding div:

![Image](https://github.com/user-attachments/assets/7da58f17-d88a-4c19-a02e-0b67a9e0c52d)
