### ISSUE TITLE
useApplyCartLinesChange hook throws "Could not apply line item changes" error in Shop Pay

### ISSUE THREAD

**Issue by nboliver** [Shopify/ui-extensions#919]
## Please list the package(s) involved in the issue, and include the version you are using

```
"@shopify/app": "3.45.1",
"@shopify/checkout-ui-extensions-react": "^0.24.0",
"@shopify/cli": "3.45.1",
"@shopify/shopify_function": "^0.0.3",
"javy": "^0.1.0",
"react": "^17.0.2"
```

## Describe the bug

In addition to #845, there are similar issues with UI extensions that leverage the `useApplyCartLinesChange` hook in Shop Pay checkout. Both issues have error messages that don't add any extra context for debugging, so it's difficult to tell what's going on.
The extension has a button that should swap the variants on each line item when clicked. In Shop Pay, the `useApplyCartLinesChange` hook results in the following response when trying to add the new variant and remove the old one: 

```
[
    {
        "type": "error",
        "message": "Could not apply line item changes"
    },
    {
        "type": "error",
        "message": "Could not apply line item changes"
    }
]
```

This is the function for swapping the variants: 

```
  async function updateLineItems() {
      const results = [];
      for (const cartLine of cartLines) {
        const productId = cartLine.merchandise.product.id;
        const currentLineId = cartLine.id;
        const quantity = cartLine.quantity;
        const attributes = cartLine.attributes;
        const targetProduct = products.find(({ id }) => id === productId);
        const newVariant = targetProduct?.variants?.nodes?.find((variant) =>
          variant?.selectedOptions?.some(
            (option) =>
              option?.name === 'Region' && option?.value === regionValue
          )
        );

        const added = await applyCartLinesChange({
          type: 'addCartLine',
          merchandiseId: newVariant.id,
          quantity,
          attributes,
        });

        const removed = await applyCartLinesChange({
          type: 'removeCartLine',
          id: currentLineId,
          quantity,
        });

        results.push(added, removed);
      }

      return results;
    }
```

## Steps to reproduce the behavior:

1. Create an extension with a button that swaps variants based on a specific option value
1. Add the extension to the Shop Pay checkout
2. Test the button in the Shop Pay checkout (test mode) and see the error happen.

## Expected behavior

Line items should be able to be swapped. The same cart and same action works fine in the regular checkout, so the appears to be something related to Shop Pay.

## Screenshots

I'm happy to DM a video of the issue. The checkout contains information that I'd prefer not to post publicly. 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/3094055/236376297-4199034d-8942-47f9-ac3b-732533ceb217.png">

**Comment by jamesvidler** [comment]
Thank you for bringing this to our attention. We'll look into this.

**Comment by nboliver** [comment]
@jamesvidler Any update on this issue? It's still happening in production stores: 
<img width="644" alt="image" src="https://github.com/Shopify/ui-extensions/assets/3094055/b625e29c-b100-407c-9f0d-9bdbfe5f9aa3">
I can share more specific details privately if you need them.

**Comment by dnagoda** [comment]
@nboliver I still want to figure out the underlying issue, but one workaround that might be worth trying is to use a `updateCartLine` instead of an add and remove. Something like this based on the code you provided above:
```
await applyCartLinesChange({
  type: 'updateCartLine',
  id: currentLineId,
  merchandiseId: newVariant.id
});
```

**Comment by nboliver** [comment]
@dnagoda Initial testing looks like using `updateCartLine` fixes the issue. Thanks for the assistance.
