### ISSUE TITLE
useOrder hook always returns undefined on Firefox

### ISSUE THREAD

**Issue by etay2000** [Shopify/ui-extensions#927]
checkout-ui-extensions-react V0.26.1

## Describe the bug

The useOrder hook always returns undefined on Firefox after the order has been submitted. It works on Safari and returns 
the Order object as expected.

1. Use the code from the order status page extensions example https://shopify.dev/docs/apps/checkout/order-status-page/getting-started
2. Test on Firefox and useOrder will always return undefined after refreshing the page.
3. Test on Safari and useOrder will return the Order object as expected after refreshing the page.l

I would expect useOrder to work the same on both Firefox and Safari.

**Comment by jun-shop** [comment]
@alxclark and @jmp-shopify can we have someone look into this soon?

**Comment by jmp-shopify** [comment]
Hi @etay2000! 

Thanks for the report. I tried reproducing the issue using Firefox v113 and the `useOrder()` seems to be okay. 

Is there any chance your URL in Firefox contained `/thank-you` when this happened?

**Comment by jmp-shopify** [comment]
Hi @etay2000!

Thanks for the followup. The presence of `/thank-you` makes sense as to why `useOrder()` return value would be `undefined`. Additionally, the `/order-status` URL is formatted slightly differently so the redirect back to the dev store is also expected.

Did you use the `?prevent_order_redirect=true` [query param](https://shopify.dev/docs/apps/checkout/order-status-page/getting-started#step-8-test-your-survey) on Firefox by any chance?

**Comment by etay2000** [comment]
Thanks @jmp-shopify, I don't recall every adding that query param, but after adding ?prevent_order_redirect=false, everything works as expected and I am able to see the order status page! Thanks for the quick response!

**Comment by jmp-shopify** [comment]
Hi @etay2000!

I'm glad that worked! The `prevent_order_redirect` flag is stored in a cookie; all it takes is one wayward query param to set it and you'll remain on the `/thank-you` URL until it's explicitly unset (or the cookie is deleted). 

I'll make a note to update our docs as it's not clear this is persisted, nor is it apparent this flag is active from the UI.

I'll mark this as resolved. If you run into any other issues please feel free to open a new issue!
