### ISSUE TITLE
addCartLine with sellingPlanId increments versus adding (in certain cases)

### ISSUE THREAD

**Issue by cpeddecord** [Shopify/ui-extensions#931]
## Please list the package(s) involved in the issue, and include the version you are using

`checkout-ui-extensions@0.26.1`

## Describe the bug

reported here: https://github.com/Shopify/ui-extensions/issues/709#issuecomment-1542608269

adding a second variant with a sellingPlanId to a cart with a product without a sellingPlanId only increments the quantity

**Comment by cpeddecord** [comment]
@catalin-invisible a fix went out that should address in part your bug as documented. There seems to be a more generic bug with adding two or more line items simultaneously that I found in my testing.

**Comment by catalin-invisible** [comment]
@cpeddecord I noticed in the `What’s new for partners and developers at Shopify` newsletter that access to selling plans in checkout extensions is now possible.

I've checked again the ability to write the `sellingPlanId`, but the issue doesn't seem to be fixed.

Thank you

**Comment by catalin-invisible** [comment]
Both the original issue, where the problem was described in [this video](https://github.com/Shopify/ui-extensions/issues/709#issuecomment-1542608269), and this issue have been closed, but the problem still persists:

When using `addCartLine` with a `sellingPlanId`, the product is not being added to cart.

**Comment by catalin-invisible** [comment]
> @catalin-invisible we have an internal issue tracking this work, is your comment [here](https://github.com/Shopify/ui-extensions/issues/709#issuecomment-2218719254) a different issue?

no, it's the same

**Comment by catalin-invisible** [comment]
any chance you can estimate when this will have a fix? we have clients that want to migrate from legacy checkout to checkout ui extensions, but since they use subscriptions (using `sellingPlanId`) our product will no longer work properly
