### ISSUE TITLE
Unable to access storeAvailabilty using the Storefront API

### ISSUE THREAD

**Issue by robinhosanee** [Shopify/ui-extensions#934]
### **Checkout UI Extension**

**Packages:**

Shopify CLI 3.45.1
Shopify Checkout 0.24.0
React 18.0.0

 const targetInfo = useTarget();
**When running this query**
  query(
    `query($ids: [ID!]!) {
        nodes(ids: $ids) {
          ... on ProductVariant {
            id
            sku
            barcode
            storeAvailability(first: 1) {
              edges {
                node {
                  available
                  pickUpTime
                  location {
                    name
                  }
                }
              }
            }
          }
        }
      }
    `,
      {
      variables: { ids: targetInfo.lines[0].merchandise.id }, 
      }
      )
**The following error is thrown**
{"data":{"nodes":[null]},"errors":[{"message":"Access denied for storeAvailability field. Required access: `unauthenticated_read_product_pickup_locations` access scope.","locations":[{"line":7,"column":13}],"path":["nodes",0,"storeAvailability"],"extensions":{"code":"ACCESS_DENIED","documentation":"https://shopify.dev/api/usage/access-scopes","requiredAccess":"`unauthenticated_read_product_pickup_locations` access scope."}}]}

**shopify.app.toml includes the following scope:**
unauthenticated_read_product_pickup_locations

**shopify.ui.extenstion.toml includes following capabilities:**
network_access = true
block_progress = true
api_access = true

Expecting access to the pickup location information.

**Comment by dnagoda** [comment]
@robinhosanee I'm going to close this issue, but please let me know if you decide to submit and enhancement request.
