### ISSUE TITLE
Access Admin API from checkout extension

### ISSUE THREAD

**Issue by etay2000** [Shopify/ui-extensions#945]
checkout-ui-extensions

I could not find any information on accessing the Admin API from a checkout extension. I would like to be able to add order metafields from a checkout extension. For example attaching survey results to a Order metafield.  Is this currently possible or any plans to support in the future?

**Comment by etay2000** [comment]
Thanks @gil-- ,

I'll look into it, I appreciate the info!

**Comment by danielbixel** [comment]
@gil-- Thanks for providing a hint to solve my problem.

In a checkout extension, I need to access information about the inventory levels. 
As I learned I cannot query these directly from the extension.

I saw your suggestion to make a route in the backend available, which queries the information and sends it back to
the extension.

But I am running into authentication issues.

`023-06-06 00:27:46 │ backend    │ [shopify-app/INFO] Running validateAuthenticatedSession
2023-06-06 00:27:46 │ backend    │ [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=undefined | {shop: undefined}
2023-06-06 00:27:46 │ backend    │ [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: false}
2023-06-06 00:27:46 │ backend    │ [shopify-app/ERROR] No shop provided to redirect to auth`

Do you by any chance have a code snippet to help me make such a request?

Here is a part of the checkout UI extension

`{useSessionToken} from "@shopify/checkout-ui-extensions-react";
const sessionTokenGetter = useSessionToken();
const sessionToken = await sessionTokenGetter.get();

            <Button
                kind='secondary'
                onPress={async () => {
                    const sessionToken = await sessionTokenGetter.get();
                    console.log("Session token:", sessionToken);

                    const response = await fetch(
                        "https://moisture-grant-jill-teenage.trycloudflare.com/api/products/count",
                        {
                            headers: {
                                "X-Shopify-Access-Token": { sessionToken },
                            },
                        }
                    );
                    console.log(response);
                }}
            >
                call 
            </Button>
`
And here is the route from the initial shopify app template

`
app.get("/api/products/count", async (_req, res) => {
    const countData = await shopify.api.rest.Product.count({
        session: res.locals.shopify.session,
    });
    res.status(200).send(countData);
});
`


Any help is very appreciated.

Thanks

**Comment by etay2000** [comment]
@danielbixel Try this: 

```
headers: {
        Authorization: `Bearer ${token}`
      }

**Comment by danielbixel** [comment]
Thats it! Thanks @etay2000 ! You made my day.

> but depending on how you implement, it could be a security concern.

Just thinking .. How could this become a security concern?
