### ISSUE TITLE
Modal component escape button issue

### ISSUE THREAD

**Issue by dmitryartemiev** [Shopify/ui-extensions#980]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/checkout-ui-extensions-react": "^0.26.2"

## Describe the bug

The Modal component's escape button does not function correctly if padding is not specified. More specifically, it lies beneath content blocks and there's no way to set its z-index.

## Steps to reproduce the behavior:

1.Import and initialize the Modal component.
2.Do not set the padding or title for the Modal.
3.Add some content to Modal component.
4.Try clicking the escape button.

## Expected behavior

Regardless of the padding specified for the Modal component, the escape button should function as expected and not be obstructed by content blocks. The escape button should have a higher z-index to ensure it's accessible.

## Screenshots

1.The escape button works only in green (padding) area.
![image](https://github.com/Shopify/ui-extensions/assets/69965225/eb829d7a-b4c3-4f1b-b7a6-081f429041d4)

2.The escape button is under the image and there is no way to set z-index to it.
![image](https://github.com/Shopify/ui-extensions/assets/69965225/69ff8efd-3efd-4c3a-8b32-47814c62b7ce)

## Additional context

This issue arises in scenarios where the Modal's padding isn't specified. As a workaround, one could set the padding to ensure the escape button works. However, this isn't ideal, as it forces developers to always specify padding for the Modal, which may not be necessary or desired for all use cases. The issue seems to lie with how the z-index for the escape button is being set.

**Comment by jffortier** [comment]
@dmitryartemiev Thanks for the detailed description of the issue. Our team will look into a fix.

**Comment by rv15hwakarthik** [comment]
We are also facing the same issue. The workaround we used was to pass title prop as an empty string.

**Comment by jun-shop** [comment]
👋 this should now be fixed. Please feel free to reopen should you find any other issues
